In [1]:
%load_ext sql 
%sql postgresql://postgres:842657913@localhost/bd_jeff

In [2]:
%%sql
drop table titanic;
drop table trajet; 
drop table Passagers;

 * postgresql://postgres:***@localhost/bd_jeff
Done.

InternalError: (psycopg2.errors.DependentObjectsStillExist) ERREUR:  n'a pas pu supprimer table trajet car d'autres objets en dépendent
DETAIL:  contrainte passagers_passengerid_fkey sur table passagers dépend de table trajet
HINT:  Utilisez DROP ... CASCADE pour supprimer aussi les objets dépendants.

[SQL: drop table trajet;]
(Background on this error at: http://sqlalche.me/e/14/2j85)

Phase 2 SAE BDD : 


Rayane ABED
Anis LADADA
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJSzWp4YybYQ_q_yFQVNrmPyxeTu_AEp0img&usqp=CAU)
Nous avons créer 3 tables.
Dans la premiére Table que nous avons nommé "Passagers":

Nous avons 5 attributs.

'Name' : avec le type varchar(chaine de caracteres) qui est elle une clé primaire car elle n'a ni emplacement vide (not null) ni de tuples repetitives (c'est a dire qu'il ya que des tuples uniques).Cet attribut liste tous les prenoms des passagers.

'Sex' : avec le type varchar(10), cet attribut correspond au sexe des passagers si il est 'male' ou 'female'.

'Age' :  il est de type Float(un nombre a virgule), c'est l'age des passagers.

'SibSp' :  de type integer (valeur entiere) cet attribut indique le nombre d'epoux/femmes parmi les passagers. 

'Parch' :  egalement de type interger et indique le nombre de parents ou enfants passagers.

Dans la dexieme table que nous avons nommé "Trajet":

Nous avons aussi 5 attributs.

'PassengerID' :  de type interger cet attribut est aussi la clé primaire (elle a aucun emplacement vide et tous les tuples sont uniques), cet attribut associe une valeur entiere propre à chaque passager

'Pclass' :  de type int(variant de 1 à 3) qui quant à lui indique le niveau de classe du passager en fonction de leurs moyens.

'Ticket' : de type varchar qui correspond tout simplement au numéro du passager.

'Fare' : de type float(nombre à virgules), Cet attribut indique le prix payé par un passager pour effectuer la croisière titanic.

'Cabin' : de type varchar chaine de caractère ou str) liste la/les cabine(s) associés au passagers. 

Pour finir, la dernière que nous avons nommé “titanic" est composée de 4 attributs:

'Name' : de type varchar(str) qui dans ce tableau ci est une clé étrangère(une clé étrangère est une clé primaire dans une autre relation/table)

'Passengerld' : de type integer qui est lui aussi une clé étrangère (car déjà primaire dans la relation “Trajet").

'Survived' : de type integer(variants de 0 à 1).Si le chiffre correspond à 1, le passager a survécu et si le chiffre correspond à 0 alors il n’a pas survécu.

'embarked' : de type varchar(str) qui attribue des lettres aux embarcations.


(NB:Les clés primaires et étrangères sont très utiles pour faire des jointures entre les différentes relations/tables)

Voici ci-dessous Notre Script : creé

In [52]:
%%sql 
drop table if exists titanic;
drop table if exists passagers;
drop table if exists trajet;

create table Trajet(                    
        PassengerId int not null,
        Pclass int,
        Ticket varchar(50),
        Fare float,
        Cabin varchar(20),
        primary key(PassengerId));

create table Passagers(  
        PassengerId int not null,
        name varchar(100) not null,
        Sex varchar(10),
        Age float,
        SibSp int,
        Parch int,
        primary key(Name),
        foreign key(PassengerId) references Trajet(PassengerId));

create table titanic(       
        PassengerId int not null,
        Name varchar(100) not null,
        Survived char(4),
        Embarked varchar(1),
        foreign key(Name) references Passagers(Name),
        foreign key(PassengerId) references Trajet(PassengerId));

 * postgresql://postgres:***@localhost/bd_jeff
Done.
Done.
Done.
Done.
Done.
Done.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [53]:
def parse_line(ligne, sep, num_colonne, ty):  # Programme du Cours 7 'Tableaux' 'Lecture et écriture formatée'
    li = ligne.split(sep)                     # Pour lire le contenu du Fichier 'titanic_train.csv'
    if ty == "int":
        return (int(li[num_colonne]))
    elif ty == "float":
        return (float(li[num_colonne]))
    elif ty == "str":
        return (li[num_colonne])
    elif ty == "bool":
        return (bool(li[num_colonne]))
    else:
        print("Erreur type non reconnu.")


f_input = open( 'titanic_train.csv' , 'r') # On Ouvre le fichier en 'Read' pour lire les données et les 
                                           # mémoriser dans les variables qui represente les attributs du fichier csv.
PassengerID = []
Survived = []
Pclass = []
name1 = []
name2 = []
name3 = []
Sex = []
Age = []
SibSp = []
Parch = []
Ticket = []
Fare = []
Cabin = []
Embarked = []
nameF = []
f_input.readline()
li = f_input.readline()
while( '' != li ) :        # ecrit les données memorisé dans les tableau des variables
    PassengerID.append(parse_line(li, ',', 0, "int"))
    Survived.append(parse_line(li, ',', 1, "str"))
    Pclass.append(parse_line(li, ',', 2, "int"))
    name1.append(parse_line(li, ',', 3, "str"))
    name2.append(parse_line(li, ',', 4, "str"))
    Sex.append(parse_line(li, ',', 5, "str"))
    Age.append(parse_line(li, ',', 6, "str"))
    SibSp.append(parse_line(li, ',', 7, "int"))
    Parch.append(parse_line(li, ',', 8, "int"))
    Ticket.append(parse_line(li, ',', 9, "str"))
    Fare.append(parse_line(li, ',', 10, "float"))
    Cabin.append(parse_line(li, ',', 11, "str"))
    Embarked.append(parse_line(li, ',', 12, "str"))
    li = f_input.readline() 
f_input.close() # on ferme le fichier 'titanic_train.csv'

i = 0                       # Impossible d'afficher le 'name' complet 
while i < len(name1) :      # j'ai du faire un mini programme pour faire en sorte que le name apparaisse completement
    name3.append(name1[i] + name2[i]) # 
    i = i + 1


f_output = open('TRAJET.csv', 'w') # Ouverture du fichier TRAJET.csv ou Creation de celui-ci si il est inexistant
i = 0
while i < len(PassengerID):
    f_output.write (str(PassengerID[i]) + ',' + str(Pclass[i]) + ',' + Ticket[i] + ',' + str(Fare[i]) + ',' + Cabin[i] + '\n')
    i = i + 1
f_output.close()

f_output = open('PASSAGERS.csv', 'w') # Ouverture du fichier PASSAGERS.csv ou Creation de celui-ci si il est inexistant
i = 0
while i < len(PassengerID) :
    f_output.write (str(PassengerID[i]) + ',' + name3[i] + ',' + Sex[i] + ',' + Age[i] + ',' + str(SibSp[i]) + ',' + str(Parch[i]) + '\n')
    i = i + 1
f_output.close()


f_output = open('TITANIC.csv', 'w') # Ouverture du fichier TITANIC.csv ou Creation de celui-ci si il est inexistant
i = 0
while i < len(PassengerID):
    f_output.write (str(PassengerID[i]) + ',' + str(name3[i]) + ',' + (Survived[i]) + ',' + str(Embarked[i]))
    i = i + 1
f_output.close()

In [54]:
%%sql
\d

 * postgresql://postgres:***@localhost/bd_jeff
9 rows affected.

[('public', 'avions', 'table', 'postgres'),
 ('public', 'clients', 'table', 'postgres'),
 ('public', 'defclasses', 'table', 'postgres'),
 ('public', 'passagers', 'table', 'postgres'),
 ('public', 'pilotes', 'table', 'postgres'),
 ('public', 'reservations', 'table', 'postgres'),
 ('public', 'titanic', 'table', 'postgres'),
 ('public', 'trajet', 'table', 'postgres'),
 ('public', 'vols', 'table', 'postgres')]

In [56]:
%%sql
\copy trajet from 'C:\Users\eegor\Desktop\lol\TRAJET.csv' delimiter ',' NULL AS '';

 * postgresql://postgres:***@localhost/bd_jeff
0 rows affected.

[]

In [57]:
%%sql
SELECT * FROM TRAJET;

 * postgresql://postgres:***@localhost/bd_jeff
891 rows affected.

[(1, 3, 'A/5 21171', 7.25, None),
 (2, 1, 'PC 17599', 71.2833, 'C85'),
 (3, 3, 'STON/O2. 3101282', 7.925, None),
 (4, 1, '113803', 53.1, 'C123'),
 (5, 3, '373450', 8.05, None),
 (6, 3, '330877', 8.4583, None),
 (7, 1, '17463', 51.8625, 'E46'),
 (8, 3, '349909', 21.075, None),
 (9, 3, '347742', 11.1333, None),
 (10, 2, '237736', 30.0708, None),
 (11, 3, 'PP 9549', 16.7, 'G6'),
 (12, 1, '113783', 26.55, 'C103'),
 (13, 3, 'A/5. 2151', 8.05, None),
 (14, 3, '347082', 31.275, None),
 (15, 3, '350406', 7.8542, None),
 (16, 2, '248706', 16.0, None),
 (17, 3, '382652', 29.125, None),
 (18, 2, '244373', 13.0, None),
 (19, 3, '345763', 18.0, None),
 (20, 3, '2649', 7.225, None),
 (21, 2, '239865', 26.0, None),
 (22, 2, '248698', 13.0, 'D56'),
 (23, 3, '330923', 8.0292, None),
 (24, 1, '113788', 35.5, 'A6'),
 (25, 3, '349909', 21.075, None),
 (26, 3, '347077', 31.3875, None),
 (27, 3, '2631', 7.225, None),
 (28, 1, '19950', 263.0, 'C23 C25 C27'),
 (29, 3, '330959', 7.8792, None),
 (30, 3, '349216', 7.8958, None),
 (31, 1, 'PC 17601', 27.7208, None),
 (32, 1, 'PC 17569', 146.5208, 'B78'),
 (33, 3, '335677', 7.75, None),
 (34, 2, 'C.A. 24579', 10.5, None),
 (35, 1, 'PC 17604', 82.1708, None),
 (36, 1, '113789', 52.0, None),
 (37, 3, '2677', 7.2292, None),
 (38, 3, 'A./5. 2152', 8.05, None),
 (39, 3, '345764', 18.0, None),
 (40, 3, '2651', 11.2417, None),
 (41, 3, '7546', 9.475, None),
 (42, 2, '11668', 21.0, None),
 (43, 3, '349253', 7.8958, None),
 (44, 2, 'SC/Paris 2123', 41.5792, None),
 (45, 3, '330958', 7.8792, None),
 (46, 3, 'S.C./A.4. 23567', 8.05, None),
 (47, 3, '370371', 15.5, None),
 (48, 3, '14311', 7.75, None),
 (49, 3, '2662', 21.6792, None),
 (50, 3, '349237', 17.8, None),
 (51, 3, '3101295', 39.6875, None),
 (52, 3, 'A/4. 39886', 7.8, None),
 (53, 1, 'PC 17572', 76.7292, 'D33'),
 (54, 2, '2926', 26.0, None),
 (55, 1, '113509', 61.9792, 'B30'),
 (56, 1, '19947', 35.5, 'C52'),
 (57, 2, 'C.A. 31026', 10.5, None),
 (58, 3, '2697', 7.2292, None),
 (59, 2, 'C.A. 34651', 27.75, None),
 (60, 3, 'CA 2144', 46.9, None),
 (61, 3, '2669', 7.2292, None),
 (62, 1, '113572', 80.0, 'B28'),
 (63, 1, '36973', 83.475, 'C83'),
 (64, 3, '347088', 27.9, None),
 (65, 1, 'PC 17605', 27.7208, None),
 (66, 3, '2661', 15.2458, None),
 (67, 2, 'C.A. 29395', 10.5, 'F33'),
 (68, 3, 'S.P. 3464', 8.1583, None),
 (69, 3, '3101281', 7.925, None),
 (70, 3, '315151', 8.6625, None),
 (71, 2, 'C.A. 33111', 10.5, None),
 (72, 3, 'CA 2144', 46.9, None),
 (73, 2, 'S.O.C. 14879', 73.5, None),
 (74, 3, '2680', 14.4542, None),
 (75, 3, '1601', 56.4958, None),
 (76, 3, '348123', 7.65, 'F G73'),
 (77, 3, '349208', 7.8958, None),
 (78, 3, '374746', 8.05, None),
 (79, 2, '248738', 29.0, None),
 (80, 3, '364516', 12.475, None),
 (81, 3, '345767', 9.0, None),
 (82, 3, '345779', 9.5, None),
 (83, 3, '330932', 7.7875, None),
 (84, 1, '113059', 47.1, None),
 (85, 2, 'SO/C 14885', 10.5, None),
 (86, 3, '3101278', 15.85, None),
 (87, 3, 'W./C. 6608', 34.375, None),
 (88, 3, 'SOTON/OQ 392086', 8.05, None),
 (89, 1, '19950', 263.0, 'C23 C25 C27'),
 (90, 3, '343275', 8.05, None),
 (91, 3, '343276', 8.05, None),
 (92, 3, '347466', 7.8542, None),
 (93, 1, 'W.E.P. 5734', 61.175, 'E31'),
 (94, 3, 'C.A. 2315', 20.575, None),
 (95, 3, '364500', 7.25, None),
 (96, 3, '374910', 8.05, None),
 (97, 1, 'PC 17754', 34.6542, 'A5'),
 (98, 1, 'PC 17759', 63.3583, 'D10 D12'),
 (99, 2, '231919', 23.0, None),
 (100, 2, '244367', 26.0, None),
 (101, 3, '349245', 7.8958, None),
 (102, 3, '349215', 7.8958, None),
 (103, 1, '35281', 77.2875, 'D26'),
 (104, 3, '7540', 8.6542, None),
 (105, 3, '3101276', 7.925, None),
 (106, 3, '349207', 7.8958, None),
 (107, 3, '343120', 7.65, None),
 (108, 3, '312991', 7.775, None),
 (109, 3, '349249', 7.8958, None),
 (110, 3, '371110', 24.15, None),
 (111, 1, '110465', 52.0, 'C110'),
 (112, 3, '2665', 14.4542, None),
 (113, 3, '324669', 8.05, None),
 (114, 3, '4136', 9.825, None),
 (115, 3, '2627', 14.4583, None),
 (116, 3, 'STON/O 2. 3101294', 7.925, None),
 (117, 3, '370369', 7.75, None),
 (118, 2, '11668', 21.0, None),
 (119, 1, 'PC 17558', 247.5208, 'B58 B60'),
 (120, 3, '347082', 31.275, None),
 (121, 2, 'S.O.C. 14879', 73.5, None),
 (122, 3, 'A4. 54510', 8.05, None),
 (123, 2, '237736', 30.0708, None),
 (124, 2, '27267', 13.0, 'E101'),
 (125, 1, '35281', 77.2875, 'D26'),
 (126, 3, '2651', 11.2417, None),
 (127, 3, '370372', 7.75, None),
 (128, 3, 'C 17369', 7.1417, None),
 (129, 3, '2668', 22.3583, 'F E69'),
 (130, 3, '347061', 6.975, None),
 (131, 3, '349241', 7.8958, None),
 (132, 3, 'SOTON/O.Q. 3101307', 7.05, None),
 (133, 3, 'A/5. 3337', 14.5, None),
 (134, 2, '228414', 26.0, None),
 (135, 2, 'C.A. 29178', 13.0, None),
 (136, 2, 'SC/PARIS 2133', 15.0458, None),
 (137, 1, '11752', 26.2833, 'D47'),
 (138, 1, '113803', 53.1, 'C123'),
 (139, 3, '7534', 9.2167, None),
 (140, 1, 'PC 17593', 79.2, 'B86'),
 (141, 3, '2678', 15.2458, None),
 (142, 3, '347081', 7.75, None),
 (143, 3, 'STON/O2. 3101279', 15.85, None),
 (144, 3, '365222', 6.75, None),
 (145, 2, '231945', 11.5, None),
 (146, 2, 'C.A. 33112', 36.75, None),
 (147, 3, '350043', 7.7958, None),
 (148, 3, 'W./C. 6608', 34.375, None),
 (149, 2, '230080', 26.0, 'F2'),
 (150, 2, '244310', 13.0, None),
 (151, 2, 'S.O.P. 1166', 12.525, None),
 (152, 1, '113776', 66.6, 'C2'),
 (153, 3, 'A.5. 11206', 8.05, None),
 (154, 3, 'A/5. 851', 14.5, None),
 (155, 3, 'Fa 265302', 7.3125, None),
 (156, 1, 'PC 17597', 61.3792, None),
 (157, 3, '35851', 7.7333, None),
 (158, 3, 'SOTON/OQ 392090', 8.05, None),
 (159, 3, '315037', 8.6625, None),
 (160, 3, 'CA. 2343', 69.55, None),
 (161, 3, '371362', 16.1, None),
 (162, 2, 'C.A. 33595', 15.75, None),
 (163, 3, '347068', 7.775, None),
 (164, 3, '315093', 8.6625, None),
 (165, 3, '3101295', 39.6875, None),
 (166, 3, '363291', 20.525, None),
 (167, 1, '113505', 55.0, 'E33'),
 (168, 3, '347088', 27.9, None),
 (169, 1, 'PC 17318', 25.925, None),
 (170, 3, '1601', 56.4958, None),
 (171, 1, '111240', 33.5, 'B19'),
 (172, 3, '382652', 29.125, None),
 (173, 3, '347742', 11.1333, None),
 (174, 3, 'STON/O 2. 3101280', 7.925, None),
 (175, 1, '17764', 30.6958, 'A7'),
 (176, 3, '350404', 7.8542, None),
 (177, 3, '4133', 25.4667, None),
 (178, 1, 'PC 17595', 28.7125, 'C49'),
 (179, 2, '250653', 13.0, None),
 (180, 3, 'LINE', 0.0, None),
 (181, 3, 'CA. 2343', 69.55, None),
 (182, 2, 'SC/PARIS 2131', 15.05, None),
 (183, 3, '347077', 31.3875, None),
 (184, 2, '230136', 39.0, 'F4'),
 (185, 3, '315153', 22.025, None),
 (186, 1, '113767', 50.0, 'A32'),
 (187, 3, '370365', 15.5, None),
 (188, 1, '111428', 26.55, None),
 (189, 3, '364849', 15.5, None),
 (190, 3, '349247', 7.8958, None),
 (191, 2, '234604', 13.0, None),
 (192, 2, '28424', 13.0, None),
 (193, 3, '350046', 7.8542, None),
 (194, 2, '230080', 26.0, 'F2'),
 (195, 1, 'PC 17610', 27.7208, 'B4'),
 (196, 1, 'PC 17569', 146.5208, 'B80'),
 (197, 3, '368703', 7.75, None),
 (198, 3, '4579', 8.4042, None),
 (199, 3, '370370', 7.75, None),
 (200, 2, '248747', 13.0, None),
 (201, 3, '345770', 9.5, None),
 (202, 3, 'CA. 2343', 69.55, None),
 (203, 3, '3101264', 6.4958, None),
 (204, 3, '2628', 7.225, None),
 (205, 3, 'A/5 3540', 8.05, None),
 (206, 3, '347054', 10.4625, 'G6'),
 (207, 3, '3101278', 15.85, None),
 (208, 3, '2699', 18.7875, None),
 (209, 3, '367231', 7.75, None),
 (210, 1, '112277', 31.0, 'A31'),
 (211, 3, 'SOTON/O.Q. 3101311', 7.05, None),
 (212, 2, 'F.C.C. 13528', 21.0, None),
 (213, 3, 'A/5 21174', 7.25, None),
 (214, 2, '250646', 13.0, None),
 (215, 3, '367229', 7.75, None),
 (216, 1, '35273', 113.275, 'D36'),
 (217, 3, 'STON/O2. 3101283', 7.925, None),
 (218, 2, '243847', 27.0, None),
 (219, 1, '11813', 76.2917, 'D15'),
 (220, 2, 'W/C 14208', 10.5, None),
 (221, 3, 'SOTON/OQ 392089', 8.05, None),
 (222, 2, '220367', 13.0, None),
 (223, 3, '21440', 8.05, None),
 (224, 3, '349234', 7.8958, None),
 (225, 1, '19943', 90.0, 'C93'),
 (226, 3, 'PP 4348', 9.35, None),
 (227, 2, 'SW/PP 751', 10.5, None),
 (228, 3, 'A/5 21173', 7.25, None),
 (229, 2, '236171', 13.0, None),
 (230, 3, '4133', 25.4667, None),
 (231, 1, '36973', 83.475, 'C83'),
 (232, 3, '347067', 7.775, None),
 (233, 2, '237442', 13.5, None),
 (234, 3, '347077', 31.3875, None),
 (235, 2, 'C.A. 29566', 10.5, None),
 (236, 3, 'W./C. 6609', 7.55, None),
 (237, 2, '26707', 26.0, None),
 (238, 2, 'C.A. 31921', 26.25, None),
 (239, 2, '28665', 10.5, None),
 (240, 2, 'SCO/W 1585', 12.275, None),
 (241, 3, '2665', 14.4542, None),
 (242, 3, '367230', 15.5, None),
 (243, 2, 'W./C. 14263', 10.5, None),
 (244, 3, 'STON/O 2. 3101275', 7.125, None),
 (245, 3, '2694', 7.225, None),
 (246, 1, '19928', 90.0, 'C78'),
 (247, 3, '347071', 7.775, None),
 (248, 2, '250649', 14.5, None),
 (249, 1, '11751', 52.5542, 'D35'),
 (250, 2, '244252', 26.0, None),
 (251, 3, '362316', 7.25, None),
 (252, 3, '347054', 10.4625, 'G6'),
 (253, 1, '113514', 26.55, 'C87'),
 (254, 3, 'A/5. 3336', 16.1, None),
 (255, 3, '370129', 20.2125, None),
 (256, 3, '2650', 15.2458, None),
 (257, 1, 'PC 17585', 79.2, None),
 (258, 1, '110152', 86.5, 'B77'),
 (259, 1, 'PC 17755', 512.3292, None),
 (260, 2, '230433', 26.0, None),
 (261, 3, '384461', 7.75, None),
 (262, 3, '347077', 31.3875, None),
 (263, 1, '110413', 79.65, 'E67'),
 (264, 1, '112059', 0.0, 'B94'),
 (265, 3, '382649', 7.75, None),
 (266, 2, 'C.A. 17248', 10.5, None),
 (267, 3, '3101295', 39.6875, None),
 (268, 3, '347083', 7.775, None),
 (269, 1, 'PC 17582', 153.4625, 'C125'),
 (270, 1, 'PC 17760', 135.6333, 'C99'),
 (271, 1, '113798', 31.0, None),
 (272, 3, 'LINE', 0.0, None),
 (273, 2, '250644', 19.5, None),
 (274, 1, 'PC 17596', 29.7, 'C118'),
 (275, 3, '370375', 7.75, None),
 (276, 1, '13502', 77.9583, 'D7'),
 (277, 3, '347073', 7.75, None),
 (278, 2, '239853', 0.0, None),
 (279, 3, '382652', 29.125, None),
 (280, 3, 'C.A. 2673', 20.25, None),
 (281, 3, '336439', 7.75, None),
 (282, 3, '347464', 7.8542, None),
 (283, 3, '345778', 9.5, None),
 (284, 3, 'A/5. 10482', 8.05, None),
 (285, 1, '113056', 26.0, 'A19'),
 (286, 3, '349239', 8.6625, None),
 (287, 3, '345774', 9.5, None),
 (288, 3, '349206', 7.8958, None),
 (289, 2, '237798', 13.0, None),
 (290, 3, '370373', 7.75, None),
 (291, 1, '19877', 78.85, None),
 (292, 1, '11967', 91.0792, 'B49'),
 (293, 2, 'SC/Paris 2163', 12.875, 'D'),
 (294, 3, '349236', 8.85, None),
 (295, 3, '349233', 7.8958, None),
 (296, 1, 'PC 17612', 27.7208, None),
 (297, 3, '2693', 7.2292, None),
 (298, 1, '113781', 151.55, 'C22 C26'),
 (299, 1, '19988', 30.5, 'C106'),
 (300, 1, 'PC 17558', 247.5208, 'B58 B60'),
 (301, 3, '9234', 7.75, None),
 (302, 3, '367226', 23.25, None),
 (303, 3, 'LINE', 0.0, None),
 (304, 2, '226593', 12.35, 'E101'),
 (305, 3, 'A/5 2466', 8.05, None),
 (306, 1, '113781', 151.55, 'C22 C26'),
 (307, 1, '17421', 110.8833, None),
 (308, 1, 'PC 17758', 108.9, 'C65'),
 (309, 2, 'P/PP 3381', 24.0, None),
 (310, 1, 'PC 17485', 56.9292, 'E36'),
 (311, 1, '11767', 83.1583, 'C54'),
 (312, 1, 'PC 17608', 262.375, 'B57 B59 B63 B66'),
 (313, 2, '250651', 26.0, None),
 (314, 3, '349243', 7.8958, None),
 (315, 2, 'F.C.C. 13529', 26.25, None),
 (316, 3, '347470', 7.8542, None),
 (317, 2, '244367', 26.0, None),
 (318, 2, '29011', 14.0, None),
 (319, 1, '36928', 164.8667, 'C7'),
 (320, 1, '16966', 134.5, 'E34'),
 (321, 3, 'A/5 21172', 7.25, None),
 (322, 3, '349219', 7.8958, None),
 (323, 2, '234818', 12.35, None),
 (324, 2, '248738', 29.0, None),
 (325, 3, 'CA. 2343', 69.55, None),
 (326, 1, 'PC 17760', 135.6333, 'C32'),
 (327, 3, '345364', 6.2375, None),
 (328, 2, '28551', 13.0, 'D'),
 (329, 3, '363291', 20.525, None),
 (330, 1, '111361', 57.9792, 'B18'),
 (331, 3, '367226', 23.25, None),
 (332, 1, '113043', 28.5, 'C124'),
 (333, 1, 'PC 17582', 153.4625, 'C91'),
 (334, 3, '345764', 18.0, None),
 (335, 1, 'PC 17611', 133.65, None),
 (336, 3, '349225', 7.8958, None),
 (337, 1, '113776', 66.6, 'C2'),
 (338, 1, '16966', 134.5, 'E40'),
 (339, 3, '7598', 8.05, None),
 (340, 1, '113784', 35.5, 'T'),
 (341, 2, '230080', 26.0, 'F2'),
 (342, 1, '19950', 263.0, 'C23 C25 C27'),
 (343, 2, '248740', 13.0, None),
 (344, 2, '244361', 13.0, None),
 (345, 2, '229236', 13.0, None),
 (346, 2, '248733', 13.0, 'F33'),
 (347, 2, '31418', 13.0, None),
 (348, 3, '386525', 16.1, None),
 (349, 3, 'C.A. 37671', 15.9, None),
 (350, 3, '315088', 8.6625, None),
 (351, 3, '7267', 9.225, None),
 (352, 1, '113510', 35.0, 'C128'),
 (353, 3, '2695', 7.2292, None),
 (354, 3, '349237', 17.8, None),
 (355, 3, '2647', 7.225, None),
 (356, 3, '345783', 9.5, None),
 (357, 1, '113505', 55.0, 'E33'),
 (358, 2, '237671', 13.0, None),
 (359, 3, '330931', 7.8792, None),
 (360, 3, '330980', 7.8792, None),
 (361, 3, '347088', 27.9, None),
 (362, 2, 'SC/PARIS 2167', 27.7208, None),
 (363, 3, '2691', 14.4542, None),
 (364, 3, 'SOTON/O.Q. 3101310', 7.05, None),
 (365, 3, '370365', 15.5, None),
 (366, 3, 'C 7076', 7.25, None),
 (367, 1, '110813', 75.25, 'D37'),
 (368, 3, '2626', 7.2292, None),
 (369, 3, '14313', 7.75, None),
 (370, 1, 'PC 17477', 69.3, 'B35'),
 (371, 1, '11765', 55.4417, 'E50'),
 (372, 3, '3101267', 6.4958, None),
 (373, 3, '323951', 8.05, None),
 (374, 1, 'PC 17760', 135.6333, None),
 (375, 3, '349909', 21.075, None),
 (376, 1, 'PC 17604', 82.1708, None),
 (377, 3, 'C 7077', 7.25, None),
 (378, 1, '113503', 211.5, 'C82'),
 (379, 3, '2648', 4.0125, None),
 (380, 3, '347069', 7.775, None),
 (381, 1, 'PC 17757', 227.525, None),
 (382, 3, '2653', 15.7417, None),
 (383, 3, 'STON/O 2. 3101293', 7.925, None),
 (384, 1, '113789', 52.0, None),
 (385, 3, '349227', 7.8958, None),
 (386, 2, 'S.O.C. 14879', 73.5, None),
 (387, 3, 'CA 2144', 46.9, None),
 (388, 2, '27849', 13.0, None),
 (389, 3, '367655', 7.7292, None),
 (390, 2, 'SC 1748', 12.0, None),
 (391, 1, '113760', 120.0, 'B96 B98'),
 (392, 3, '350034', 7.7958, None),
 (393, 3, '3101277', 7.925, None),
 (394, 1, '35273', 113.275, 'D36'),
 (395, 3, 'PP 9549', 16.7, 'G6'),
 (396, 3, '350052', 7.7958, None),
 (397, 3, '350407', 7.8542, None),
 (398, 2, '28403', 26.0, None),
 (399, 2, '244278', 10.5, None),
 (400, 2, '240929', 12.65, None),
 (401, 3, 'STON/O 2. 3101289', 7.925, None),
 (402, 3, '341826', 8.05, None),
 (403, 3, '4137', 9.825, None),
 (404, 3, 'STON/O2. 3101279', 15.85, None),
 (405, 3, '315096', 8.6625, None),
 (406, 2, '28664', 21.0, None),
 (407, 3, '347064', 7.75, None),
 (408, 2, '29106', 18.75, None),
 (409, 3, '312992', 7.775, None),
 (410, 3, '4133', 25.4667, None),
 (411, 3, '349222', 7.8958, None),
 (412, 3, '394140', 6.8583, None),
 (413, 1, '19928', 90.0, 'C78'),
 (414, 2, '239853', 0.0, None),
 (415, 3, 'STON/O 2. 3101269', 7.925, None),
 (416, 3, '343095', 8.05, None),
 (417, 2, '28220', 32.5, None),
 (418, 2, '250652', 13.0, None),
 (419, 2, '28228', 13.0, None),
 (420, 3, '345773', 24.15, None),
 (421, 3, '349254', 7.8958, None),
 (422, 3, 'A/5. 13032', 7.7333, None),
 (423, 3, '315082', 7.875, None),
 (424, 3, '347080', 14.4, None),
 (425, 3, '370129', 20.2125, None),
 (426, 3, 'A/4. 34244', 7.25, None),
 (427, 2, '2003', 26.0, None),
 (428, 2, '250655', 26.0, None),
 (429, 3, '364851', 7.75, None),
 (430, 3, 'SOTON/O.Q. 392078', 8.05, 'E10'),
 (431, 1, '110564', 26.55, 'C52'),
 (432, 3, '376564', 16.1, None),
 (433, 2, 'SC/AH 3085', 26.0, None),
 (434, 3, 'STON/O 2. 3101274', 7.125, None),
 (435, 1, '13507', 55.9, 'E44'),
 (436, 1, '113760', 120.0, 'B96 B98'),
 (437, 3, 'W./C. 6608', 34.375, None),
 (438, 2, '29106', 18.75, None),
 (439, 1, '19950', 263.0, 'C23 C25 C27'),
 (440, 2, 'C.A. 18723', 10.5, None),
 (441, 2, 'F.C.C. 13529', 26.25, None),
 (442, 3, '345769', 9.5, None),
 (443, 3, '347076', 7.775, None),
 (444, 2, '230434', 13.0, None),
 (445, 3, '65306', 8.1125, None),
 (446, 1, '33638', 81.8583, 'A34'),
 (447, 2, '250644', 19.5, None),
 (448, 1, '113794', 26.55, None),
 (449, 3, '2666', 19.2583, None),
 (450, 1, '113786', 30.5, 'C104'),
 (451, 2, 'C.A. 34651', 27.75, None),
 (452, 3, '65303', 19.9667, None),
 (453, 1, '113051', 27.75, 'C111'),
 (454, 1, '17453', 89.1042, 'C92'),
 (455, 3, 'A/5 2817', 8.05, None),
 (456, 3, '349240', 7.8958, None),
 (457, 1, '13509', 26.55, 'E38'),
 (458, 1, '17464', 51.8625, 'D21'),
 (459, 2, 'F.C.C. 13531', 10.5, None),
 (460, 3, '371060', 7.75, None),
 (461, 1, '19952', 26.55, 'E12'),
 (462, 3, '364506', 8.05, None),
 (463, 1, '111320', 38.5, 'E63'),
 (464, 2, '234360', 13.0, None),
 (465, 3, 'A/S 2816', 8.05, None),
 (466, 3, 'SOTON/O.Q. 3101306', 7.05, None),
 (467, 2, '239853', 0.0, None),
 (468, 1, '113792', 26.55, None),
 (469, 3, '36209', 7.725, None),
 (470, 3, '2666', 19.2583, None),
 (471, 3, '323592', 7.25, None),
 (472, 3, '315089', 8.6625, None),
 (473, 2, 'C.A. 34651', 27.75, None),
 (474, 2, 'SC/AH Basle 541', 13.7917, 'D'),
 (475, 3, '7553', 9.8375, None),
 (476, 1, '110465', 52.0, 'A14'),
 (477, 2, '31027', 21.0, None),
 (478, 3, '3460', 7.0458, None),
 (479, 3, '350060', 7.5208, None),
 (480, 3, '3101298', 12.2875, None),
 (481, 3, 'CA 2144', 46.9, None),
 (482, 2, '239854', 0.0, None),
 (483, 3, 'A/5 3594', 8.05, None),
 (484, 3, '4134', 9.5875, None),
 (485, 1, '11967', 91.0792, 'B49'),
 (486, 3, '4133', 25.4667, None),
 (487, 1, '19943', 90.0, 'C93'),
 (488, 1, '11771', 29.7, 'B37'),
 (489, 3, 'A.5. 18509', 8.05, None),
 (490, 3, 'C.A. 37671', 15.9, None),
 (491, 3, '65304', 19.9667, None),
 (492, 3, 'SOTON/OQ 3101317', 7.25, None),
 (493, 1, '113787', 30.5, 'C30'),
 (494, 1, 'PC 17609', 49.5042, None),
 (495, 3, 'A/4 45380', 8.05, None),
 (496, 3, '2627', 14.4583, None),
 (497, 1, '36947', 78.2667, 'D20'),
 (498, 3, 'C.A. 6212', 15.1, None),
 (499, 1, '113781', 151.55, 'C22 C26'),
 (500, 3, '350035', 7.7958, None),
 (501, 3, '315086', 8.6625, None),
 (502, 3, '364846', 7.75, None),
 (503, 3, '330909', 7.6292, None),
 (504, 3, '4135', 9.5875, None),
 (505, 1, '110152', 86.5, 'B79'),
 (506, 1, 'PC 17758', 108.9, 'C65'),
 (507, 2, '26360', 26.0, None),
 (508, 1, '111427', 26.55, None),
 (509, 3, 'C 4001', 22.525, None),
 (510, 3, '1601', 56.4958, None),
 (511, 3, '382651', 7.75, None),
 (512, 3, 'SOTON/OQ 3101316', 8.05, None),
 (513, 1, 'PC 17473', 26.2875, 'E25'),
 (514, 1, 'PC 17603', 59.4, None),
 (515, 3, '349209', 7.4958, None),
 (516, 1, '36967', 34.0208, 'D46'),
 (517, 2, 'C.A. 34260', 10.5, 'F33'),
 (518, 3, '371110', 24.15, None),
 (519, 2, '226875', 26.0, None),
 (520, 3, '349242', 7.8958, None),
 (521, 1, '12749', 93.5, 'B73'),
 (522, 3, '349252', 7.8958, None),
 (523, 3, '2624', 7.225, None),
 (524, 1, '111361', 57.9792, 'B18'),
 (525, 3, '2700', 7.2292, None),
 (526, 3, '367232', 7.75, None),
 (527, 2, 'W./C. 14258', 10.5, None),
 (528, 1, 'PC 17483', 221.7792, 'C95'),
 (529, 3, '3101296', 7.925, None),
 (530, 2, '29104', 11.5, None),
 (531, 2, '26360', 26.0, None),
 (532, 3, '2641', 7.2292, None),
 (533, 3, '2690', 7.2292, None),
 (534, 3, '2668', 22.3583, None),
 (535, 3, '315084', 8.6625, None),
 (536, 2, 'F.C.C. 13529', 26.25, None),
 (537, 1, '113050', 26.55, 'B38'),
 (538, 1, 'PC 17761', 106.425, None),
 (539, 3, '364498', 14.5, None),
 (540, 1, '13568', 49.5, 'B39'),
 (541, 1, 'WE/P 5735', 71.0, 'B22'),
 (542, 3, '347082', 31.275, None),
 (543, 3, '347082', 31.275, None),
 (544, 2, '2908', 26.0, None),
 (545, 1, 'PC 17761', 106.425, 'C86'),
 (546, 1, '693', 26.0, None),
 (547, 2, '2908', 26.0, None),
 (548, 2, 'SC/PARIS 2146', 13.8625, None),
 (549, 3, '363291', 20.525, None),
 (550, 2, 'C.A. 33112', 36.75, None),
 (551, 1, '17421', 110.8833, 'C70'),
 (552, 2, '244358', 26.0, None),
 (553, 3, '330979', 7.8292, None),
 (554, 3, '2620', 7.225, None),
 (555, 3, '347085', 7.775, None),
 (556, 1, '113807', 26.55, None),
 (557, 1, '11755', 39.6, 'A16'),
 (558, 1, 'PC 17757', 227.525, None),
 (559, 1, '110413', 79.65, 'E67'),
 (560, 3, '345572', 17.4, None),
 (561, 3, '372622', 7.75, None),
 (562, 3, '349251', 7.8958, None),
 (563, 2, '218629', 13.5, None),
 (564, 3, 'SOTON/OQ 392082', 8.05, None),
 (565, 3, 'SOTON/O.Q. 392087', 8.05, None),
 (566, 3, 'A/4 48871', 24.15, None),
 (567, 3, '349205', 7.8958, None),
 (568, 3, '349909', 21.075, None),
 (569, 3, '2686', 7.2292, None),

In [58]:
%%sql
\copy passagers from 'C:\Users\eegor\Desktop\lol\PASSAGERS.csv' delimiter ',' NULL AS '';

 * postgresql://postgres:***@localhost/bd_jeff
0 rows affected.

[]

In [59]:
%%sql
select * from PASSAGERS;

 * postgresql://postgres:***@localhost/bd_jeff
891 rows affected.

[(1, '"Braund Mr. Owen Harris"', 'male', 22.0, 1, 0),
 (2, '"Cumings Mrs. John Bradley (Florence Briggs Thayer)"', 'female', 38.0, 1, 0),
 (3, '"Heikkinen Miss. Laina"', 'female', 26.0, 0, 0),
 (4, '"Futrelle Mrs. Jacques Heath (Lily May Peel)"', 'female', 35.0, 1, 0),
 (5, '"Allen Mr. William Henry"', 'male', 35.0, 0, 0),
 (6, '"Moran Mr. James"', 'male', None, 0, 0),
 (7, '"McCarthy Mr. Timothy J"', 'male', 54.0, 0, 0),
 (8, '"Palsson Master. Gosta Leonard"', 'male', 2.0, 3, 1),
 (9, '"Johnson Mrs. Oscar W (Elisabeth Vilhelmina Berg)"', 'female', 27.0, 0, 2),
 (10, '"Nasser Mrs. Nicholas (Adele Achem)"', 'female', 14.0, 1, 0),
 (11, '"Sandstrom Miss. Marguerite Rut"', 'female', 4.0, 1, 1),
 (12, '"Bonnell Miss. Elizabeth"', 'female', 58.0, 0, 0),
 (13, '"Saundercock Mr. William Henry"', 'male', 20.0, 0, 0),
 (14, '"Andersson Mr. Anders Johan"', 'male', 39.0, 1, 5),
 (15, '"Vestrom Miss. Hulda Amanda Adolfina"', 'female', 14.0, 0, 0),
 (16, '"Hewlett Mrs. (Mary D Kingcome) "', 'female', 55.0, 0, 0),
 (17, '"Rice Master. Eugene"', 'male', 2.0, 4, 1),
 (18, '"Williams Mr. Charles Eugene"', 'male', None, 0, 0),
 (19, '"Vander Planke Mrs. Julius (Emelia Maria Vandemoortele)"', 'female', 31.0, 1, 0),
 (20, '"Masselmani Mrs. Fatima"', 'female', None, 0, 0),
 (21, '"Fynney Mr. Joseph J"', 'male', 35.0, 0, 0),
 (22, '"Beesley Mr. Lawrence"', 'male', 34.0, 0, 0),
 (23, '"McGowan Miss. Anna ""Annie"""', 'female', 15.0, 0, 0),
 (24, '"Sloper Mr. William Thompson"', 'male', 28.0, 0, 0),
 (25, '"Palsson Miss. Torborg Danira"', 'female', 8.0, 3, 1),
 (26, '"Asplund Mrs. Carl Oscar (Selma Augusta Emilia Johansson)"', 'female', 38.0, 1, 5),
 (27, '"Emir Mr. Farred Chehab"', 'male', None, 0, 0),
 (28, '"Fortune Mr. Charles Alexander"', 'male', 19.0, 3, 2),
 (29, '"O\'Dwyer Miss. Ellen ""Nellie"""', 'female', None, 0, 0),
 (30, '"Todoroff Mr. Lalio"', 'male', None, 0, 0),
 (31, '"Uruchurtu Don. Manuel E"', 'male', 40.0, 0, 0),
 (32, '"Spencer Mrs. William Augustus (Marie Eugenie)"', 'female', None, 1, 0),
 (33, '"Glynn Miss. Mary Agatha"', 'female', None, 0, 0),
 (34, '"Wheadon Mr. Edward H"', 'male', 66.0, 0, 0),
 (35, '"Meyer Mr. Edgar Joseph"', 'male', 28.0, 1, 0),
 (36, '"Holverson Mr. Alexander Oskar"', 'male', 42.0, 1, 0),
 (37, '"Mamee Mr. Hanna"', 'male', None, 0, 0),
 (38, '"Cann Mr. Ernest Charles"', 'male', 21.0, 0, 0),
 (39, '"Vander Planke Miss. Augusta Maria"', 'female', 18.0, 2, 0),
 (40, '"Nicola-Yarred Miss. Jamila"', 'female', 14.0, 1, 0),
 (41, '"Ahlin Mrs. Johan (Johanna Persdotter Larsson)"', 'female', 40.0, 1, 0),
 (42, '"Turpin Mrs. William John Robert (Dorothy Ann Wonnacott)"', 'female', 27.0, 1, 0),
 (43, '"Kraeff Mr. Theodor"', 'male', None, 0, 0),
 (44, '"Laroche Miss. Simonne Marie Anne Andree"', 'female', 3.0, 1, 2),
 (45, '"Devaney Miss. Margaret Delia"', 'female', 19.0, 0, 0),
 (46, '"Rogers Mr. William John"', 'male', None, 0, 0),
 (47, '"Lennon Mr. Denis"', 'male', None, 1, 0),
 (48, '"O\'Driscoll Miss. Bridget"', 'female', None, 0, 0),
 (49, '"Samaan Mr. Youssef"', 'male', None, 2, 0),
 (50, '"Arnold-Franchi Mrs. Josef (Josefine Franchi)"', 'female', 18.0, 1, 0),
 (51, '"Panula Master. Juha Niilo"', 'male', 7.0, 4, 1),
 (52, '"Nosworthy Mr. Richard Cater"', 'male', 21.0, 0, 0),
 (53, '"Harper Mrs. Henry Sleeper (Myna Haxtun)"', 'female', 49.0, 1, 0),
 (54, '"Faunthorpe Mrs. Lizzie (Elizabeth Anne Wilkinson)"', 'female', 29.0, 1, 0),
 (55, '"Ostby Mr. Engelhart Cornelius"', 'male', 65.0, 0, 1),
 (56, '"Woolner Mr. Hugh"', 'male', None, 0, 0),
 (57, '"Rugg Miss. Emily"', 'female', 21.0, 0, 0),
 (58, '"Novel Mr. Mansouer"', 'male', 28.5, 0, 0),
 (59, '"West Miss. Constance Mirium"', 'female', 5.0, 1, 2),
 (60, '"Goodwin Master. William Frederick"', 'male', 11.0, 5, 2),
 (61, '"Sirayanian Mr. Orsen"', 'male', 22.0, 0, 0),
 (62, '"Icard Miss. Amelie"', 'female', 38.0, 0, 0),
 (63, '"Harris Mr. Henry Birkhardt"', 'male', 45.0, 1, 0),
 (64, '"Skoog Master. Harald"', 'male', 4.0, 3, 2),
 (65, '"Stewart Mr. Albert A"', 'male', None, 0, 0),
 (66, '"Moubarek Master. Gerios"', 'male', None, 1, 1),
 (67, '"Nye Mrs. (Elizabeth Ramell)"', 'female', 29.0, 0, 0),
 (68, '"Crease Mr. Ernest James"', 'male', 19.0, 0, 0),
 (69, '"Andersson Miss. Erna Alexandra"', 'female', 17.0, 4, 2),
 (70, '"Kink Mr. Vincenz"', 'male', 26.0, 2, 0),
 (71, '"Jenkin Mr. Stephen Curnow"', 'male', 32.0, 0, 0),
 (72, '"Goodwin Miss. Lillian Amy"', 'female', 16.0, 5, 2),
 (73, '"Hood Mr. Ambrose Jr"', 'male', 21.0, 0, 0),
 (74, '"Chronopoulos Mr. Apostolos"', 'male', 26.0, 1, 0),
 (75, '"Bing Mr. Lee"', 'male', 32.0, 0, 0),
 (76, '"Moen Mr. Sigurd Hansen"', 'male', 25.0, 0, 0),
 (77, '"Staneff Mr. Ivan"', 'male', None, 0, 0),
 (78, '"Moutal Mr. Rahamin Haim"', 'male', None, 0, 0),
 (79, '"Caldwell Master. Alden Gates"', 'male', 0.83, 0, 2),
 (80, '"Dowdell Miss. Elizabeth"', 'female', 30.0, 0, 0),
 (81, '"Waelens Mr. Achille"', 'male', 22.0, 0, 0),
 (82, '"Sheerlinck Mr. Jan Baptist"', 'male', 29.0, 0, 0),
 (83, '"McDermott Miss. Brigdet Delia"', 'female', None, 0, 0),
 (84, '"Carrau Mr. Francisco M"', 'male', 28.0, 0, 0),
 (85, '"Ilett Miss. Bertha"', 'female', 17.0, 0, 0),
 (86, '"Backstrom Mrs. Karl Alfred (Maria Mathilda Gustafsson)"', 'female', 33.0, 3, 0),
 (87, '"Ford Mr. William Neal"', 'male', 16.0, 1, 3),
 (88, '"Slocovski Mr. Selman Francis"', 'male', None, 0, 0),
 (89, '"Fortune Miss. Mabel Helen"', 'female', 23.0, 3, 2),
 (90, '"Celotti Mr. Francesco"', 'male', 24.0, 0, 0),
 (91, '"Christmann Mr. Emil"', 'male', 29.0, 0, 0),
 (92, '"Andreasson Mr. Paul Edvin"', 'male', 20.0, 0, 0),
 (93, '"Chaffee Mr. Herbert Fuller"', 'male', 46.0, 1, 0),
 (94, '"Dean Mr. Bertram Frank"', 'male', 26.0, 1, 2),
 (95, '"Coxon Mr. Daniel"', 'male', 59.0, 0, 0),
 (96, '"Shorney Mr. Charles Joseph"', 'male', None, 0, 0),
 (97, '"Goldschmidt Mr. George B"', 'male', 71.0, 0, 0),
 (98, '"Greenfield Mr. William Bertram"', 'male', 23.0, 0, 1),
 (99, '"Doling Mrs. John T (Ada Julia Bone)"', 'female', 34.0, 0, 1),
 (100, '"Kantor Mr. Sinai"', 'male', 34.0, 1, 0),
 (101, '"Petranec Miss. Matilda"', 'female', 28.0, 0, 0),
 (102, '"Petroff Mr. Pastcho (""Pentcho"")"', 'male', None, 0, 0),
 (103, '"White Mr. Richard Frasar"', 'male', 21.0, 0, 1),
 (104, '"Johansson Mr. Gustaf Joel"', 'male', 33.0, 0, 0),
 (105, '"Gustafsson Mr. Anders Vilhelm"', 'male', 37.0, 2, 0),
 (106, '"Mionoff Mr. Stoytcho"', 'male', 28.0, 0, 0),
 (107, '"Salkjelsvik Miss. Anna Kristine"', 'female', 21.0, 0, 0),
 (108, '"Moss Mr. Albert Johan"', 'male', None, 0, 0),
 (109, '"Rekic Mr. Tido"', 'male', 38.0, 0, 0),
 (110, '"Moran Miss. Bertha"', 'female', None, 1, 0),
 (111, '"Porter Mr. Walter Chamberlain"', 'male', 47.0, 0, 0),
 (112, '"Zabour Miss. Hileni"', 'female', 14.5, 1, 0),
 (113, '"Barton Mr. David John"', 'male', 22.0, 0, 0),
 (114, '"Jussila Miss. Katriina"', 'female', 20.0, 1, 0),
 (115, '"Attalah Miss. Malake"', 'female', 17.0, 0, 0),
 (116, '"Pekoniemi Mr. Edvard"', 'male', 21.0, 0, 0),
 (117, '"Connors Mr. Patrick"', 'male', 70.5, 0, 0),
 (118, '"Turpin Mr. William John Robert"', 'male', 29.0, 1, 0),
 (119, '"Baxter Mr. Quigg Edmond"', 'male', 24.0, 0, 1),
 (120, '"Andersson Miss. Ellis Anna Maria"', 'female', 2.0, 4, 2),
 (121, '"Hickman Mr. Stanley George"', 'male', 21.0, 2, 0),
 (122, '"Moore Mr. Leonard Charles"', 'male', None, 0, 0),
 (123, '"Nasser Mr. Nicholas"', 'male', 32.5, 1, 0),
 (124, '"Webber Miss. Susan"', 'female', 32.5, 0, 0),
 (125, '"White Mr. Percival Wayland"', 'male', 54.0, 0, 1),
 (126, '"Nicola-Yarred Master. Elias"', 'male', 12.0, 1, 0),
 (127, '"McMahon Mr. Martin"', 'male', None, 0, 0),
 (128, '"Madsen Mr. Fridtjof Arne"', 'male', 24.0, 0, 0),
 (129, '"Peter Miss. Anna"', 'female', None, 1, 1),
 (130, '"Ekstrom Mr. Johan"', 'male', 45.0, 0, 0),
 (131, '"Drazenoic Mr. Jozef"', 'male', 33.0, 0, 0),
 (132, '"Coelho Mr. Domingos Fernandeo"', 'male', 20.0, 0, 0),
 (133, '"Robins Mrs. Alexander A (Grace Charity Laury)"', 'female', 47.0, 1, 0),
 (134, '"Weisz Mrs. Leopold (Mathilde Francoise Pede)"', 'female', 29.0, 1, 0),
 (135, '"Sobey Mr. Samuel James Hayden"', 'male', 25.0, 0, 0),
 (136, '"Richard Mr. Emile"', 'male', 23.0, 0, 0),
 (137, '"Newsom Miss. Helen Monypeny"', 'female', 19.0, 0, 2),
 (138, '"Futrelle Mr. Jacques Heath"', 'male', 37.0, 1, 0),
 (139, '"Osen Mr. Olaf Elon"', 'male', 16.0, 0, 0),
 (140, '"Giglio Mr. Victor"', 'male', 24.0, 0, 0),
 (141, '"Boulos Mrs. Joseph (Sultana)"', 'female', None, 0, 2),
 (142, '"Nysten Miss. Anna Sofia"', 'female', 22.0, 0, 0),
 (143, '"Hakkarainen Mrs. Pekka Pietari (Elin Matilda Dolck)"', 'female', 24.0, 1, 0),
 (144, '"Burke Mr. Jeremiah"', 'male', 19.0, 0, 0),
 (145, '"Andrew Mr. Edgardo Samuel"', 'male', 18.0, 0, 0),
 (146, '"Nicholls Mr. Joseph Charles"', 'male', 19.0, 1, 1),
 (147, '"Andersson Mr. August Edvard (""Wennerstrom"")"', 'male', 27.0, 0, 0),
 (148, '"Ford Miss. Robina Maggie ""Ruby"""', 'female', 9.0, 2, 2),
 (149, '"Navratil Mr. Michel (""Louis M Hoffman"")"', 'male', 36.5, 0, 2),
 (150, '"Byles Rev. Thomas Roussel Davids"', 'male', 42.0, 0, 0),
 (151, '"Bateman Rev. Robert James"', 'male', 51.0, 0, 0),
 (152, '"Pears Mrs. Thomas (Edith Wearne)"', 'female', 22.0, 1, 0),
 (153, '"Meo Mr. Alfonzo"', 'male', 55.5, 0, 0),
 (154, '"van Billiard Mr. Austin Blyler"', 'male', 40.5, 0, 2),
 (155, '"Olsen Mr. Ole Martin"', 'male', None, 0, 0),
 (156, '"Williams Mr. Charles Duane"', 'male', 51.0, 0, 1),
 (157, '"Gilnagh Miss. Katherine ""Katie"""', 'female', 16.0, 0, 0),
 (158, '"Corn Mr. Harry"', 'male', 30.0, 0, 0),
 (159, '"Smiljanic Mr. Mile"', 'male', None, 0, 0),
 (160, '"Sage Master. Thomas Henry"', 'male', None, 8, 2),
 (161, '"Cribb Mr. John Hatfield"', 'male', 44.0, 0, 1),
 (162, '"Watt Mrs. James (Elizabeth ""Bessie"" Inglis Milne)"', 'female', 40.0, 0, 0),
 (163, '"Bengtsson Mr. John Viktor"', 'male', 26.0, 0, 0),
 (164, '"Calic Mr. Jovo"', 'male', 17.0, 0, 0),
 (165, '"Panula Master. Eino Viljami"', 'male', 1.0, 4, 1),
 (166, '"Goldsmith Master. Frank John William ""Frankie"""', 'male', 9.0, 0, 2),
 (167, '"Chibnall Mrs. (Edith Martha Bowerman)"', 'female', None, 0, 1),
 (168, '"Skoog Mrs. William (Anna Bernhardina Karlsson)"', 'female', 45.0, 1, 4),
 (169, '"Baumann Mr. John D"', 'male', None, 0, 0),
 (170, '"Ling Mr. Lee"', 'male', 28.0, 0, 0),
 (171, '"Van der hoef Mr. Wyckoff"', 'male', 61.0, 0, 0),
 (172, '"Rice Master. Arthur"', 'male', 4.0, 4, 1),
 (173, '"Johnson Miss. Eleanor Ileen"', 'female', 1.0, 1, 1),
 (174, '"Sivola Mr. Antti Wilhelm"', 'male', 21.0, 0, 0),
 (175, '"Smith Mr. James Clinch"', 'male', 56.0, 0, 0),
 (176, '"Klasen Mr. Klas Albin"', 'male', 18.0, 1, 1),
 (177, '"Lefebre Master. Henry Forbes"', 'male', None, 3, 1),
 (178, '"Isham Miss. Ann Elizabeth"', 'female', 50.0, 0, 0),
 (179, '"Hale Mr. Reginald"', 'male', 30.0, 0, 0),
 (180, '"Leonard Mr. Lionel"', 'male', 36.0, 0, 0),
 (181, '"Sage Miss. Constance Gladys"', 'female', None, 8, 2),
 (182, '"Pernot Mr. Rene"', 'male', None, 0, 0),
 (183, '"Asplund Master. Clarence Gustaf Hugo"', 'male', 9.0, 4, 2),
 (184, '"Becker Master. Richard F"', 'male', 1.0, 2, 1),
 (185, '"Kink-Heilmann Miss. Luise Gretchen"', 'female', 4.0, 0, 2),
 (186, '"Rood Mr. Hugh Roscoe"', 'male', None, 0, 0),
 (187, '"O\'Brien Mrs. Thomas (Johanna ""Hannah"" Godfrey)"', 'female', None, 1, 0),
 (188, '"Romaine Mr. Charles Hallace (""Mr C Rolmane"")"', 'male', 45.0, 0, 0),
 (189, '"Bourke Mr. John"', 'male', 40.0, 1, 1),
 (190, '"Turcin Mr. Stjepan"', 'male', 36.0, 0, 0),
 (191, '"Pinsky Mrs. (Rosa)"', 'female', 32.0, 0, 0),
 (192, '"Carbines Mr. William"', 'male', 19.0, 0, 0),
 (193, '"Andersen-Jensen Miss. Carla Christine Nielsine"', 'female', 19.0, 1, 0),
 (194, '"Navratil Master. Michel M"', 'male', 3.0, 1, 1),
 (195, '"Brown Mrs. James Joseph (Margaret Tobin)"', 'female', 44.0, 0, 0),
 (196, '"Lurette Miss. Elise"', 'female', 58.0, 0, 0),
 (197, '"Mernagh Mr. Robert"', 'male', None, 0, 0),
 (198, '"Olsen Mr. Karl Siegwart Andreas"', 'male', 42.0, 0, 1),
 (199, '"Madigan Miss. Margaret ""Maggie"""', 'female', None, 0, 0),
 (200, '"Yrois Miss. Henriette (""Mrs Harbeck"")"', 'female', 24.0, 0, 0),
 (201, '"Vande Walle Mr. Nestor Cyriel"', 'male', 28.0, 0, 0),
 (202, '"Sage Mr. Frederick"', 'male', None, 8, 2),
 (203, '"Johanson Mr. Jakob Alfred"', 'male', 34.0, 0, 0),
 (204, '"Youseff Mr. Gerious"', 'male', 45.5, 0, 0),
 (205, '"Cohen Mr. Gurshon ""Gus"""', 'male', 18.0, 0, 0),
 (206, '"Strom Miss. Telma Matilda"', 'female', 2.0, 0, 1),
 (207, '"Backstrom Mr. Karl Alfred"', 'male', 32.0, 1, 0),
 (208, '"Albimona Mr. Nassef Cassem"', 'male', 26.0, 0, 0),
 (209, '"Carr Miss. Helen ""Ellen"""', 'female', 16.0, 0, 0),
 (210, '"Blank Mr. Henry"', 'male', 40.0, 0, 0),
 (211, '"Ali Mr. Ahmed"', 'male', 24.0, 0, 0),
 (212, '"Cameron Miss. Clear Annie"', 'female', 35.0, 0, 0),
 (213, '"Perkin Mr. John Henry"', 'male', 22.0, 0, 0),
 (214, '"Givard Mr. Hans Kristensen"', 'male', 30.0, 0, 0),
 (215, '"Kiernan Mr. Philip"', 'male', None, 1, 0),
 (216, '"Newell Miss. Madeleine"', 'female', 31.0, 1, 0),
 (217, '"Honkanen Miss. Eliina"', 'female', 27.0, 0, 0),
 (218, '"Jacobsohn Mr. Sidney Samuel"', 'male', 42.0, 1, 0),
 (219, '"Bazzani Miss. Albina"', 'female', 32.0, 0, 0),
 (220, '"Harris Mr. Walter"', 'male', 30.0, 0, 0),
 (221, '"Sunderland Mr. Victor Francis"', 'male', 16.0, 0, 0),
 (222, '"Bracken Mr. James H"', 'male', 27.0, 0, 0),
 (223, '"Green Mr. George Henry"', 'male', 51.0, 0, 0),
 (224, '"Nenkoff Mr. Christo"', 'male', None, 0, 0),
 (225, '"Hoyt Mr. Frederick Maxfield"', 'male', 38.0, 1, 0),
 (226, '"Berglund Mr. Karl Ivar Sven"', 'male', 22.0, 0, 0),
 (227, '"Mellors Mr. William John"', 'male', 19.0, 0, 0),
 (228, '"Lovell Mr. John Hall (""Henry"")"', 'male', 20.5, 0, 0),
 (229, '"Fahlstrom Mr. Arne Jonas"', 'male', 18.0, 0, 0),
 (230, '"Lefebre Miss. Mathilde"', 'female', None, 3, 1),
 (231, '"Harris Mrs. Henry Birkhardt (Irene Wallach)"', 'female', 35.0, 1, 0),
 (232, '"Larsson Mr. Bengt Edvin"', 'male', 29.0, 0, 0),
 (233, '"Sjostedt Mr. Ernst Adolf"', 'male', 59.0, 0, 0),
 (234, '"Asplund Miss. Lillian Gertrud"', 'female', 5.0, 4, 2),
 (235, '"Leyson Mr. Robert William Norman"', 'male', 24.0, 0, 0),
 (236, '"Harknett Miss. Alice Phoebe"', 'female', None, 0, 0),
 (237, '"Hold Mr. Stephen"', 'male', 44.0, 1, 0),
 (238, '"Collyer Miss. Marjorie ""Lottie"""', 'female', 8.0, 0, 2),
 (239, '"Pengelly Mr. Frederick William"', 'male', 19.0, 0, 0),
 (240, '"Hunt Mr. George Henry"', 'male', 33.0, 0, 0),
 (241, '"Zabour Miss. Thamine"', 'female', None, 1, 0),
 (242, '"Murphy Miss. Katherine ""Kate"""', 'female', None, 1, 0),
 (243, '"Coleridge Mr. Reginald Charles"', 'male', 29.0, 0, 0),
 (244, '"Maenpaa Mr. Matti Alexanteri"', 'male', 22.0, 0, 0),
 (245, '"Attalah Mr. Sleiman"', 'male', 30.0, 0, 0),
 (246, '"Minahan Dr. William Edward"', 'male', 44.0, 2, 0),
 (247, '"Lindahl Miss. Agda Thorilda Viktoria"', 'female', 25.0, 0, 0),
 (248, '"Hamalainen Mrs. William (Anna)"', 'female', 24.0, 0, 2),
 (249, '"Beckwith Mr. Richard Leonard"', 'male', 37.0, 1, 1),
 (250, '"Carter Rev. Ernest Courtenay"', 'male', 54.0, 1, 0),
 (251, '"Reed Mr. James George"', 'male', None, 0, 0),
 (252, '"Strom Mrs. Wilhelm (Elna Matilda Persson)"', 'female', 29.0, 1, 1),
 (253, '"Stead Mr. William Thomas"', 'male', 62.0, 0, 0),
 (254, '"Lobb Mr. William Arthur"', 'male', 30.0, 1, 0),
 (255, '"Rosblom Mrs. Viktor (Helena Wilhelmina)"', 'female', 41.0, 0, 2),
 (256, '"Touma Mrs. Darwis (Hanne Youssef Razi)"', 'female', 29.0, 0, 2),
 (257, '"Thorne Mrs. Gertrude Maybelle"', 'female', None, 0, 0),
 (258, '"Cherry Miss. Gladys"', 'female', 30.0, 0, 0),
 (259, '"Ward Miss. Anna"', 'female', 35.0, 0, 0),
 (260, '"Parrish Mrs. (Lutie Davis)"', 'female', 50.0, 0, 1),
 (261, '"Smith Mr. Thomas"', 'male', None, 0, 0),
 (262, '"Asplund Master. Edvin Rojj Felix"', 'male', 3.0, 4, 2),
 (263, '"Taussig Mr. Emil"', 'male', 52.0, 1, 1),
 (264, '"Harrison Mr. William"', 'male', 40.0, 0, 0),
 (265, '"Henry Miss. Delia"', 'female', None, 0, 0),
 (266, '"Reeves Mr. David"', 'male', 36.0, 0, 0),
 (267, '"Panula Mr. Ernesti Arvid"', 'male', 16.0, 4, 1),
 (268, '"Persson Mr. Ernst Ulrik"', 'male', 25.0, 1, 0),
 (269, '"Graham Mrs. William Thompson (Edith Junkins)"', 'female', 58.0, 0, 1),
 (270, '"Bissette Miss. Amelia"', 'female', 35.0, 0, 0),
 (271, '"Cairns Mr. Alexander"', 'male', None, 0, 0),
 (272, '"Tornquist Mr. William Henry"', 'male', 25.0, 0, 0),
 (273, '"Mellinger Mrs. (Elizabeth Anne Maidment)"', 'female', 41.0, 0, 1),
 (274, '"Natsch Mr. Charles H"', 'male', 37.0, 0, 1),
 (275, '"Healy Miss. Hanora ""Nora"""', 'female', None, 0, 0),
 (276, '"Andrews Miss. Kornelia Theodosia"', 'female', 63.0, 1, 0),
 (277, '"Lindblom Miss. Augusta Charlotta"', 'female', 45.0, 0, 0),
 (278, '"Parkes Mr. Francis ""Frank"""', 'male', None, 0, 0),
 (279, '"Rice Master. Eric"', 'male', 7.0, 4, 1),
 (280, '"Abbott Mrs. Stanton (Rosa Hunt)"', 'female', 35.0, 1, 1),
 (281, '"Duane Mr. Frank"', 'male', 65.0, 0, 0),
 (282, '"Olsson Mr. Nils Johan Goransson"', 'male', 28.0, 0, 0),
 (283, '"de Pelsmaeker Mr. Alfons"', 'male', 16.0, 0, 0),
 (284, '"Dorking Mr. Edward Arthur"', 'male', 19.0, 0, 0),
 (285, '"Smith Mr. Richard William"', 'male', None, 0, 0),
 (286, '"Stankovic Mr. Ivan"', 'male', 33.0, 0, 0),
 (287, '"de Mulder Mr. Theodore"', 'male', 30.0, 0, 0),
 (288, '"Naidenoff Mr. Penko"', 'male', 22.0, 0, 0),
 (289, '"Hosono Mr. Masabumi"', 'male', 42.0, 0, 0),
 (290, '"Connolly Miss. Kate"', 'female', 22.0, 0, 0),
 (291, '"Barber Miss. Ellen ""Nellie"""', 'female', 26.0, 0, 0),
 (292, '"Bishop Mrs. Dickinson H (Helen Walton)"', 'female', 19.0, 1, 0),
 (293, '"Levy Mr. Rene Jacques"', 'male', 36.0, 0, 0),
 (294, '"Haas Miss. Aloisia"', 'female', 24.0, 0, 0),
 (295, '"Mineff Mr. Ivan"', 'male', 24.0, 0, 0),
 (296, '"Lewy Mr. Ervin G"', 'male', None, 0, 0),
 (297, '"Hanna Mr. Mansour"', 'male', 23.5, 0, 0),
 (298, '"Allison Miss. Helen Loraine"', 'female', 2.0, 1, 2),
 (299, '"Saalfeld Mr. Adolphe"', 'male', None, 0, 0),
 (300, '"Baxter Mrs. James (Helene DeLaudeniere Chaput)"', 'female', 50.0, 0, 1),
 (301, '"Kelly Miss. Anna Katherine ""Annie Kate"""', 'female', None, 0, 0),
 (302, '"McCoy Mr. Bernard"', 'male', None, 2, 0),
 (303, '"Johnson Mr. William Cahoone Jr"', 'male', 19.0, 0, 0),
 (304, '"Keane Miss. Nora A"', 'female', None, 0, 0),
 (305, '"Williams Mr. Howard Hugh ""Harry"""', 'male', None, 0, 0),
 (306, '"Allison Master. Hudson Trevor"', 'male', 0.92, 1, 2),
 (307, '"Fleming Miss. Margaret"', 'female', None, 0, 0),
 (308, '"Penasco y Castellana Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)"', 'female', 17.0, 1, 0),
 (309, '"Abelson Mr. Samuel"', 'male', 30.0, 1, 0),
 (310, '"Francatelli Miss. Laura Mabel"', 'female', 30.0, 0, 0),
 (311, '"Hays Miss. Margaret Bechstein"', 'female', 24.0, 0, 0),
 (312, '"Ryerson Miss. Emily Borie"', 'female', 18.0, 2, 2),
 (313, '"Lahtinen Mrs. William (Anna Sylfven)"', 'female', 26.0, 1, 1),
 (314, '"Hendekovic Mr. Ignjac"', 'male', 28.0, 0, 0),
 (315, '"Hart Mr. Benjamin"', 'male', 43.0, 1, 1),
 (316, '"Nilsson Miss. Helmina Josefina"', 'female', 26.0, 0, 0),
 (317, '"Kantor Mrs. Sinai (Miriam Sternin)"', 'female', 24.0, 1, 0),
 (318, '"Moraweck Dr. Ernest"', 'male', 54.0, 0, 0),
 (319, '"Wick Miss. Mary Natalie"', 'female', 31.0, 0, 2),
 (320, '"Spedden Mrs. Frederic Oakley (Margaretta Corning Stone)"', 'female', 40.0, 1, 1),
 (321, '"Dennis Mr. Samuel"', 'male', 22.0, 0, 0),
 (322, '"Danoff Mr. Yoto"', 'male', 27.0, 0, 0),
 (323, '"Slayter Miss. Hilda Mary"', 'female', 30.0, 0, 0),
 (324, '"Caldwell Mrs. Albert Francis (Sylvia Mae Harbaugh)"', 'female', 22.0, 1, 1),
 (325, '"Sage Mr. George John Jr"', 'male', None, 8, 2),
 (326, '"Young Miss. Marie Grice"', 'female', 36.0, 0, 0),
 (327, '"Nysveen Mr. Johan Hansen"', 'male', 61.0, 0, 0),
 (328, '"Ball Mrs. (Ada E Hall)"', 'female', 36.0, 0, 0),
 (329, '"Goldsmith Mrs. Frank John (Emily Alice Brown)"', 'female', 31.0, 1, 1),
 (330, '"Hippach Miss. Jean Gertrude"', 'female', 16.0, 0, 1),

In [60]:
%%sql
\copy titanic from 'C:\Users\eegor\Desktop\lol\TITANIC.csv' delimiter ',' NULL AS '';

 * postgresql://postgres:***@localhost/bd_jeff
0 rows affected.

[]

In [72]:
%%sql
SELECT * FROM TITANIC;

 * postgresql://postgres:***@localhost/bd_jeff
891 rows affected.

[(1, '"Braund Mr. Owen Harris"', '0   ', 'S'),
 (2, '"Cumings Mrs. John Bradley (Florence Briggs Thayer)"', '1   ', 'C'),
 (3, '"Heikkinen Miss. Laina"', '1   ', 'S'),
 (4, '"Futrelle Mrs. Jacques Heath (Lily May Peel)"', '1   ', 'S'),
 (5, '"Allen Mr. William Henry"', '0   ', 'S'),
 (6, '"Moran Mr. James"', '0   ', 'Q'),
 (7, '"McCarthy Mr. Timothy J"', '0   ', 'S'),
 (8, '"Palsson Master. Gosta Leonard"', '0   ', 'S'),
 (9, '"Johnson Mrs. Oscar W (Elisabeth Vilhelmina Berg)"', '1   ', 'S'),
 (10, '"Nasser Mrs. Nicholas (Adele Achem)"', '1   ', 'C'),
 (11, '"Sandstrom Miss. Marguerite Rut"', '1   ', 'S'),
 (12, '"Bonnell Miss. Elizabeth"', '1   ', 'S'),
 (13, '"Saundercock Mr. William Henry"', '0   ', 'S'),
 (14, '"Andersson Mr. Anders Johan"', '0   ', 'S'),
 (15, '"Vestrom Miss. Hulda Amanda Adolfina"', '0   ', 'S'),
 (16, '"Hewlett Mrs. (Mary D Kingcome) "', '1   ', 'S'),
 (17, '"Rice Master. Eugene"', '0   ', 'Q'),
 (18, '"Williams Mr. Charles Eugene"', '1   ', 'S'),
 (19, '"Vander Planke Mrs. Julius (Emelia Maria Vandemoortele)"', '0   ', 'S'),
 (20, '"Masselmani Mrs. Fatima"', '1   ', 'C'),
 (21, '"Fynney Mr. Joseph J"', '0   ', 'S'),
 (22, '"Beesley Mr. Lawrence"', '1   ', 'S'),
 (23, '"McGowan Miss. Anna ""Annie"""', '1   ', 'Q'),
 (24, '"Sloper Mr. William Thompson"', '1   ', 'S'),
 (25, '"Palsson Miss. Torborg Danira"', '0   ', 'S'),
 (26, '"Asplund Mrs. Carl Oscar (Selma Augusta Emilia Johansson)"', '1   ', 'S'),
 (27, '"Emir Mr. Farred Chehab"', '0   ', 'C'),
 (28, '"Fortune Mr. Charles Alexander"', '0   ', 'S'),
 (29, '"O\'Dwyer Miss. Ellen ""Nellie"""', '1   ', 'Q'),
 (30, '"Todoroff Mr. Lalio"', '0   ', 'S'),
 (31, '"Uruchurtu Don. Manuel E"', '0   ', 'C'),
 (32, '"Spencer Mrs. William Augustus (Marie Eugenie)"', '1   ', 'C'),
 (33, '"Glynn Miss. Mary Agatha"', '1   ', 'Q'),
 (34, '"Wheadon Mr. Edward H"', '0   ', 'S'),
 (35, '"Meyer Mr. Edgar Joseph"', '0   ', 'C'),
 (36, '"Holverson Mr. Alexander Oskar"', '0   ', 'S'),
 (37, '"Mamee Mr. Hanna"', '1   ', 'C'),
 (38, '"Cann Mr. Ernest Charles"', '0   ', 'S'),
 (39, '"Vander Planke Miss. Augusta Maria"', '0   ', 'S'),
 (40, '"Nicola-Yarred Miss. Jamila"', '1   ', 'C'),
 (41, '"Ahlin Mrs. Johan (Johanna Persdotter Larsson)"', '0   ', 'S'),
 (42, '"Turpin Mrs. William John Robert (Dorothy Ann Wonnacott)"', '0   ', 'S'),
 (43, '"Kraeff Mr. Theodor"', '0   ', 'C'),
 (44, '"Laroche Miss. Simonne Marie Anne Andree"', '1   ', 'C'),
 (45, '"Devaney Miss. Margaret Delia"', '1   ', 'Q'),
 (46, '"Rogers Mr. William John"', '0   ', 'S'),
 (47, '"Lennon Mr. Denis"', '0   ', 'Q'),
 (48, '"O\'Driscoll Miss. Bridget"', '1   ', 'Q'),
 (49, '"Samaan Mr. Youssef"', '0   ', 'C'),
 (50, '"Arnold-Franchi Mrs. Josef (Josefine Franchi)"', '0   ', 'S'),
 (51, '"Panula Master. Juha Niilo"', '0   ', 'S'),
 (52, '"Nosworthy Mr. Richard Cater"', '0   ', 'S'),
 (53, '"Harper Mrs. Henry Sleeper (Myna Haxtun)"', '1   ', 'C'),
 (54, '"Faunthorpe Mrs. Lizzie (Elizabeth Anne Wilkinson)"', '1   ', 'S'),
 (55, '"Ostby Mr. Engelhart Cornelius"', '0   ', 'C'),
 (56, '"Woolner Mr. Hugh"', '1   ', 'S'),
 (57, '"Rugg Miss. Emily"', '1   ', 'S'),
 (58, '"Novel Mr. Mansouer"', '0   ', 'C'),
 (59, '"West Miss. Constance Mirium"', '1   ', 'S'),
 (60, '"Goodwin Master. William Frederick"', '0   ', 'S'),
 (61, '"Sirayanian Mr. Orsen"', '0   ', 'C'),
 (62, '"Icard Miss. Amelie"', '1   ', None),
 (63, '"Harris Mr. Henry Birkhardt"', '0   ', 'S'),
 (64, '"Skoog Master. Harald"', '0   ', 'S'),
 (65, '"Stewart Mr. Albert A"', '0   ', 'C'),
 (66, '"Moubarek Master. Gerios"', '1   ', 'C'),
 (67, '"Nye Mrs. (Elizabeth Ramell)"', '1   ', 'S'),
 (68, '"Crease Mr. Ernest James"', '0   ', 'S'),
 (69, '"Andersson Miss. Erna Alexandra"', '1   ', 'S'),
 (70, '"Kink Mr. Vincenz"', '0   ', 'S'),
 (71, '"Jenkin Mr. Stephen Curnow"', '0   ', 'S'),
 (72, '"Goodwin Miss. Lillian Amy"', '0   ', 'S'),
 (73, '"Hood Mr. Ambrose Jr"', '0   ', 'S'),
 (74, '"Chronopoulos Mr. Apostolos"', '0   ', 'C'),
 (75, '"Bing Mr. Lee"', '1   ', 'S'),
 (76, '"Moen Mr. Sigurd Hansen"', '0   ', 'S'),
 (77, '"Staneff Mr. Ivan"', '0   ', 'S'),
 (78, '"Moutal Mr. Rahamin Haim"', '0   ', 'S'),
 (79, '"Caldwell Master. Alden Gates"', '1   ', 'S'),
 (80, '"Dowdell Miss. Elizabeth"', '1   ', 'S'),
 (81, '"Waelens Mr. Achille"', '0   ', 'S'),
 (82, '"Sheerlinck Mr. Jan Baptist"', '1   ', 'S'),
 (83, '"McDermott Miss. Brigdet Delia"', '1   ', 'Q'),
 (84, '"Carrau Mr. Francisco M"', '0   ', 'S'),
 (85, '"Ilett Miss. Bertha"', '1   ', 'S'),
 (86, '"Backstrom Mrs. Karl Alfred (Maria Mathilda Gustafsson)"', '1   ', 'S'),
 (87, '"Ford Mr. William Neal"', '0   ', 'S'),
 (88, '"Slocovski Mr. Selman Francis"', '0   ', 'S'),
 (89, '"Fortune Miss. Mabel Helen"', '1   ', 'S'),
 (90, '"Celotti Mr. Francesco"', '0   ', 'S'),
 (91, '"Christmann Mr. Emil"', '0   ', 'S'),
 (92, '"Andreasson Mr. Paul Edvin"', '0   ', 'S'),
 (93, '"Chaffee Mr. Herbert Fuller"', '0   ', 'S'),
 (94, '"Dean Mr. Bertram Frank"', '0   ', 'S'),
 (95, '"Coxon Mr. Daniel"', '0   ', 'S'),
 (96, '"Shorney Mr. Charles Joseph"', '0   ', 'S'),
 (97, '"Goldschmidt Mr. George B"', '0   ', 'C'),
 (98, '"Greenfield Mr. William Bertram"', '1   ', 'C'),
 (99, '"Doling Mrs. John T (Ada Julia Bone)"', '1   ', 'S'),
 (100, '"Kantor Mr. Sinai"', '0   ', 'S'),
 (101, '"Petranec Miss. Matilda"', '0   ', 'S'),
 (102, '"Petroff Mr. Pastcho (""Pentcho"")"', '0   ', 'S'),
 (103, '"White Mr. Richard Frasar"', '0   ', 'S'),
 (104, '"Johansson Mr. Gustaf Joel"', '0   ', 'S'),
 (105, '"Gustafsson Mr. Anders Vilhelm"', '0   ', 'S'),
 (106, '"Mionoff Mr. Stoytcho"', '0   ', 'S'),
 (107, '"Salkjelsvik Miss. Anna Kristine"', '1   ', 'S'),
 (108, '"Moss Mr. Albert Johan"', '1   ', 'S'),
 (109, '"Rekic Mr. Tido"', '0   ', 'S'),
 (110, '"Moran Miss. Bertha"', '1   ', 'Q'),
 (111, '"Porter Mr. Walter Chamberlain"', '0   ', 'S'),
 (112, '"Zabour Miss. Hileni"', '0   ', 'C'),
 (113, '"Barton Mr. David John"', '0   ', 'S'),
 (114, '"Jussila Miss. Katriina"', '0   ', 'S'),
 (115, '"Attalah Miss. Malake"', '0   ', 'C'),
 (116, '"Pekoniemi Mr. Edvard"', '0   ', 'S'),
 (117, '"Connors Mr. Patrick"', '0   ', 'Q'),
 (118, '"Turpin Mr. William John Robert"', '0   ', 'S'),
 (119, '"Baxter Mr. Quigg Edmond"', '0   ', 'C'),
 (120, '"Andersson Miss. Ellis Anna Maria"', '0   ', 'S'),
 (121, '"Hickman Mr. Stanley George"', '0   ', 'S'),
 (122, '"Moore Mr. Leonard Charles"', '0   ', 'S'),
 (123, '"Nasser Mr. Nicholas"', '0   ', 'C'),
 (124, '"Webber Miss. Susan"', '1   ', 'S'),
 (125, '"White Mr. Percival Wayland"', '0   ', 'S'),
 (126, '"Nicola-Yarred Master. Elias"', '1   ', 'C'),
 (127, '"McMahon Mr. Martin"', '0   ', 'Q'),
 (128, '"Madsen Mr. Fridtjof Arne"', '1   ', 'S'),
 (129, '"Peter Miss. Anna"', '1   ', 'C'),
 (130, '"Ekstrom Mr. Johan"', '0   ', 'S'),
 (131, '"Drazenoic Mr. Jozef"', '0   ', 'C'),
 (132, '"Coelho Mr. Domingos Fernandeo"', '0   ', 'S'),
 (133, '"Robins Mrs. Alexander A (Grace Charity Laury)"', '0   ', 'S'),
 (134, '"Weisz Mrs. Leopold (Mathilde Francoise Pede)"', '1   ', 'S'),
 (135, '"Sobey Mr. Samuel James Hayden"', '0   ', 'S'),
 (136, '"Richard Mr. Emile"', '0   ', 'C'),
 (137, '"Newsom Miss. Helen Monypeny"', '1   ', 'S'),
 (138, '"Futrelle Mr. Jacques Heath"', '0   ', 'S'),
 (139, '"Osen Mr. Olaf Elon"', '0   ', 'S'),
 (140, '"Giglio Mr. Victor"', '0   ', 'C'),
 (141, '"Boulos Mrs. Joseph (Sultana)"', '0   ', 'C'),
 (142, '"Nysten Miss. Anna Sofia"', '1   ', 'S'),
 (143, '"Hakkarainen Mrs. Pekka Pietari (Elin Matilda Dolck)"', '1   ', 'S'),
 (144, '"Burke Mr. Jeremiah"', '0   ', 'Q'),
 (145, '"Andrew Mr. Edgardo Samuel"', '0   ', 'S'),
 (146, '"Nicholls Mr. Joseph Charles"', '0   ', 'S'),
 (147, '"Andersson Mr. August Edvard (""Wennerstrom"")"', '1   ', 'S'),
 (148, '"Ford Miss. Robina Maggie ""Ruby"""', '0   ', 'S'),
 (149, '"Navratil Mr. Michel (""Louis M Hoffman"")"', '0   ', 'S'),
 (150, '"Byles Rev. Thomas Roussel Davids"', '0   ', 'S'),
 (151, '"Bateman Rev. Robert James"', '0   ', 'S'),
 (152, '"Pears Mrs. Thomas (Edith Wearne)"', '1   ', 'S'),
 (153, '"Meo Mr. Alfonzo"', '0   ', 'S'),
 (154, '"van Billiard Mr. Austin Blyler"', '0   ', 'S'),
 (155, '"Olsen Mr. Ole Martin"', '0   ', 'S'),
 (156, '"Williams Mr. Charles Duane"', '0   ', 'C'),
 (157, '"Gilnagh Miss. Katherine ""Katie"""', '1   ', 'Q'),
 (158, '"Corn Mr. Harry"', '0   ', 'S'),
 (159, '"Smiljanic Mr. Mile"', '0   ', 'S'),
 (160, '"Sage Master. Thomas Henry"', '0   ', 'S'),
 (161, '"Cribb Mr. John Hatfield"', '0   ', 'S'),
 (162, '"Watt Mrs. James (Elizabeth ""Bessie"" Inglis Milne)"', '1   ', 'S'),
 (163, '"Bengtsson Mr. John Viktor"', '0   ', 'S'),
 (164, '"Calic Mr. Jovo"', '0   ', 'S'),
 (165, '"Panula Master. Eino Viljami"', '0   ', 'S'),
 (166, '"Goldsmith Master. Frank John William ""Frankie"""', '1   ', 'S'),
 (167, '"Chibnall Mrs. (Edith Martha Bowerman)"', '1   ', 'S'),
 (168, '"Skoog Mrs. William (Anna Bernhardina Karlsson)"', '0   ', 'S'),
 (169, '"Baumann Mr. John D"', '0   ', 'S'),
 (170, '"Ling Mr. Lee"', '0   ', 'S'),
 (171, '"Van der hoef Mr. Wyckoff"', '0   ', 'S'),
 (172, '"Rice Master. Arthur"', '0   ', 'Q'),
 (173, '"Johnson Miss. Eleanor Ileen"', '1   ', 'S'),
 (174, '"Sivola Mr. Antti Wilhelm"', '0   ', 'S'),
 (175, '"Smith Mr. James Clinch"', '0   ', 'C'),
 (176, '"Klasen Mr. Klas Albin"', '0   ', 'S'),
 (177, '"Lefebre Master. Henry Forbes"', '0   ', 'S'),
 (178, '"Isham Miss. Ann Elizabeth"', '0   ', 'C'),
 (179, '"Hale Mr. Reginald"', '0   ', 'S'),
 (180, '"Leonard Mr. Lionel"', '0   ', 'S'),
 (181, '"Sage Miss. Constance Gladys"', '0   ', 'S'),
 (182, '"Pernot Mr. Rene"', '0   ', 'C'),
 (183, '"Asplund Master. Clarence Gustaf Hugo"', '0   ', 'S'),
 (184, '"Becker Master. Richard F"', '1   ', 'S'),
 (185, '"Kink-Heilmann Miss. Luise Gretchen"', '1   ', 'S'),
 (186, '"Rood Mr. Hugh Roscoe"', '0   ', 'S'),
 (187, '"O\'Brien Mrs. Thomas (Johanna ""Hannah"" Godfrey)"', '1   ', 'Q'),
 (188, '"Romaine Mr. Charles Hallace (""Mr C Rolmane"")"', '1   ', 'S'),
 (189, '"Bourke Mr. John"', '0   ', 'Q'),
 (190, '"Turcin Mr. Stjepan"', '0   ', 'S'),
 (191, '"Pinsky Mrs. (Rosa)"', '1   ', 'S'),
 (192, '"Carbines Mr. William"', '0   ', 'S'),
 (193, '"Andersen-Jensen Miss. Carla Christine Nielsine"', '1   ', 'S'),
 (194, '"Navratil Master. Michel M"', '1   ', 'S'),
 (195, '"Brown Mrs. James Joseph (Margaret Tobin)"', '1   ', 'C'),
 (196, '"Lurette Miss. Elise"', '1   ', 'C'),
 (197, '"Mernagh Mr. Robert"', '0   ', 'Q'),
 (198, '"Olsen Mr. Karl Siegwart Andreas"', '0   ', 'S'),
 (199, '"Madigan Miss. Margaret ""Maggie"""', '1   ', 'Q'),
 (200, '"Yrois Miss. Henriette (""Mrs Harbeck"")"', '0   ', 'S'),
 (201, '"Vande Walle Mr. Nestor Cyriel"', '0   ', 'S'),
 (202, '"Sage Mr. Frederick"', '0   ', 'S'),
 (203, '"Johanson Mr. Jakob Alfred"', '0   ', 'S'),
 (204, '"Youseff Mr. Gerious"', '0   ', 'C'),
 (205, '"Cohen Mr. Gurshon ""Gus"""', '1   ', 'S'),
 (206, '"Strom Miss. Telma Matilda"', '0   ', 'S'),
 (207, '"Backstrom Mr. Karl Alfred"', '0   ', 'S'),
 (208, '"Albimona Mr. Nassef Cassem"', '1   ', 'C'),
 (209, '"Carr Miss. Helen ""Ellen"""', '1   ', 'Q'),
 (210, '"Blank Mr. Henry"', '1   ', 'C'),
 (211, '"Ali Mr. Ahmed"', '0   ', 'S'),
 (212, '"Cameron Miss. Clear Annie"', '1   ', 'S'),
 (213, '"Perkin Mr. John Henry"', '0   ', 'S'),
 (214, '"Givard Mr. Hans Kristensen"', '0   ', 'S'),
 (215, '"Kiernan Mr. Philip"', '0   ', 'Q'),
 (216, '"Newell Miss. Madeleine"', '1   ', 'C'),
 (217, '"Honkanen Miss. Eliina"', '1   ', 'S'),
 (218, '"Jacobsohn Mr. Sidney Samuel"', '0   ', 'S'),
 (219, '"Bazzani Miss. Albina"', '1   ', 'C'),
 (220, '"Harris Mr. Walter"', '0   ', 'S'),
 (221, '"Sunderland Mr. Victor Francis"', '1   ', 'S'),
 (222, '"Bracken Mr. James H"', '0   ', 'S'),
 (223, '"Green Mr. George Henry"', '0   ', 'S'),
 (224, '"Nenkoff Mr. Christo"', '0   ', 'S'),
 (225, '"Hoyt Mr. Frederick Maxfield"', '1   ', 'S'),
 (226, '"Berglund Mr. Karl Ivar Sven"', '0   ', 'S'),
 (227, '"Mellors Mr. William John"', '1   ', 'S'),
 (228, '"Lovell Mr. John Hall (""Henry"")"', '0   ', 'S'),
 (229, '"Fahlstrom Mr. Arne Jonas"', '0   ', 'S'),
 (230, '"Lefebre Miss. Mathilde"', '0   ', 'S'),
 (231, '"Harris Mrs. Henry Birkhardt (Irene Wallach)"', '1   ', 'S'),
 (232, '"Larsson Mr. Bengt Edvin"', '0   ', 'S'),
 (233, '"Sjostedt Mr. Ernst Adolf"', '0   ', 'S'),
 (234, '"Asplund Miss. Lillian Gertrud"', '1   ', 'S'),
 (235, '"Leyson Mr. Robert William Norman"', '0   ', 'S'),
 (236, '"Harknett Miss. Alice Phoebe"', '0   ', 'S'),
 (237, '"Hold Mr. Stephen"', '0   ', 'S'),
 (238, '"Collyer Miss. Marjorie ""Lottie"""', '1   ', 'S'),
 (239, '"Pengelly Mr. Frederick William"', '0   ', 'S'),
 (240, '"Hunt Mr. George Henry"', '0   ', 'S'),
 (241, '"Zabour Miss. Thamine"', '0   ', 'C'),
 (242, '"Murphy Miss. Katherine ""Kate"""', '1   ', 'Q'),
 (243, '"Coleridge Mr. Reginald Charles"', '0   ', 'S'),
 (244, '"Maenpaa Mr. Matti Alexanteri"', '0   ', 'S'),
 (245, '"Attalah Mr. Sleiman"', '0   ', 'C'),
 (246, '"Minahan Dr. William Edward"', '0   ', 'Q'),
 (247, '"Lindahl Miss. Agda Thorilda Viktoria"', '0   ', 'S'),
 (248, '"Hamalainen Mrs. William (Anna)"', '1   ', 'S'),
 (249, '"Beckwith Mr. Richard Leonard"', '1   ', 'S'),
 (250, '"Carter Rev. Ernest Courtenay"', '0   ', 'S'),
 (251, '"Reed Mr. James George"', '0   ', 'S'),
 (252, '"Strom Mrs. Wilhelm (Elna Matilda Persson)"', '0   ', 'S'),
 (253, '"Stead Mr. William Thomas"', '0   ', 'S'),
 (254, '"Lobb Mr. William Arthur"', '0   ', 'S'),
 (255, '"Rosblom Mrs. Viktor (Helena Wilhelmina)"', '0   ', 'S'),
 (256, '"Touma Mrs. Darwis (Hanne Youssef Razi)"', '1   ', 'C'),
 (257, '"Thorne Mrs. Gertrude Maybelle"', '1   ', 'C'),
 (258, '"Cherry Miss. Gladys"', '1   ', 'S'),
 (259, '"Ward Miss. Anna"', '1   ', 'C'),
 (260, '"Parrish Mrs. (Lutie Davis)"', '1   ', 'S'),
 (261, '"Smith Mr. Thomas"', '0   ', 'Q'),
 (262, '"Asplund Master. Edvin Rojj Felix"', '1   ', 'S'),
 (263, '"Taussig Mr. Emil"', '0   ', 'S'),
 (264, '"Harrison Mr. William"', '0   ', 'S'),
 (265, '"Henry Miss. Delia"', '0   ', 'Q'),
 (266, '"Reeves Mr. David"', '0   ', 'S'),
 (267, '"Panula Mr. Ernesti Arvid"', '0   ', 'S'),
 (268, '"Persson Mr. Ernst Ulrik"', '1   ', 'S'),
 (269, '"Graham Mrs. William Thompson (Edith Junkins)"', '1   ', 'S'),
 (270, '"Bissette Miss. Amelia"', '1   ', 'S'),
 (271, '"Cairns Mr. Alexander"', '0   ', 'S'),
 (272, '"Tornquist Mr. William Henry"', '1   ', 'S'),
 (273, '"Mellinger Mrs. (Elizabeth Anne Maidment)"', '1   ', 'S'),
 (274, '"Natsch Mr. Charles H"', '0   ', 'C'),
 (275, '"Healy Miss. Hanora ""Nora"""', '1   ', 'Q'),
 (276, '"Andrews Miss. Kornelia Theodosia"', '1   ', 'S'),
 (277, '"Lindblom Miss. Augusta Charlotta"', '0   ', 'S'),
 (278, '"Parkes Mr. Francis ""Frank"""', '0   ', 'S'),
 (279, '"Rice Master. Eric"', '0   ', 'Q'),
 (280, '"Abbott Mrs. Stanton (Rosa Hunt)"', '1   ', 'S'),
 (281, '"Duane Mr. Frank"', '0   ', 'Q'),
 (282, '"Olsson Mr. Nils Johan Goransson"', '0   ', 'S'),
 (283, '"de Pelsmaeker Mr. Alfons"', '0   ', 'S'),
 (284, '"Dorking Mr. Edward Arthur"', '1   ', 'S'),
 (285, '"Smith Mr. Richard William"', '0   ', 'S'),
 (286, '"Stankovic Mr. Ivan"', '0   ', 'C'),
 (287, '"de Mulder Mr. Theodore"', '1   ', 'S'),
 (288, '"Naidenoff Mr. Penko"', '0   ', 'S'),
 (289, '"Hosono Mr. Masabumi"', '1   ', 'S'),
 (290, '"Connolly Miss. Kate"', '1   ', 'Q'),
 (291, '"Barber Miss. Ellen ""Nellie"""', '1   ', 'S'),
 (292, '"Bishop Mrs. Dickinson H (Helen Walton)"', '1   ', 'C'),
 (293, '"Levy Mr. Rene Jacques"', '0   ', 'C'),
 (294, '"Haas Miss. Aloisia"', '0   ', 'S'),
 (295, '"Mineff Mr. Ivan"', '0   ', 'S'),
 (296, '"Lewy Mr. Ervin G"', '0   ', 'C'),
 (297, '"Hanna Mr. Mansour"', '0   ', 'C'),
 (298, '"Allison Miss. Helen Loraine"', '0   ', 'S'),
 (299, '"Saalfeld Mr. Adolphe"', '1   ', 'S'),
 (300, '"Baxter Mrs. James (Helene DeLaudeniere Chaput)"', '1   ', 'C'),
 (301, '"Kelly Miss. Anna Katherine ""Annie Kate"""', '1   ', 'Q'),
 (302, '"McCoy Mr. Bernard"', '1   ', 'Q'),
 (303, '"Johnson Mr. William Cahoone Jr"', '0   ', 'S'),
 (304, '"Keane Miss. Nora A"', '1   ', 'Q'),
 (305, '"Williams Mr. Howard Hugh ""Harry"""', '0   ', 'S'),
 (306, '"Allison Master. Hudson Trevor"', '1   ', 'S'),
 (307, '"Fleming Miss. Margaret"', '1   ', 'C'),
 (308, '"Penasco y Castellana Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)"', '1   ', 'C'),
 (309, '"Abelson Mr. Samuel"', '0   ', 'C'),
 (310, '"Francatelli Miss. Laura Mabel"', '1   ', 'C'),
 (311, '"Hays Miss. Margaret Bechstein"', '1   ', 'C'),
 (312, '"Ryerson Miss. Emily Borie"', '1   ', 'C'),
 (313, '"Lahtinen Mrs. William (Anna Sylfven)"', '0   ', 'S'),
 (314, '"Hendekovic Mr. Ignjac"', '0   ', 'S'),
 (315, '"Hart Mr. Benjamin"', '0   ', 'S'),
 (316, '"Nilsson Miss. Helmina Josefina"', '1   ', 'S'),
 (317, '"Kantor Mrs. Sinai (Miriam Sternin)"', '1   ', 'S'),
 (318, '"Moraweck Dr. Ernest"', '0   ', 'S'),
 (319, '"Wick Miss. Mary Natalie"', '1   ', 'S'),
 (320, '"Spedden Mrs. Frederic Oakley (Margaretta Corning Stone)"', '1   ', 'C'),
 (321, '"Dennis Mr. Samuel"', '0   ', 'S'),
 (322, '"Danoff Mr. Yoto"', '0   ', 'S'),
 (323, '"Slayter Miss. Hilda Mary"', '1   ', 'Q'),
 (324, '"Caldwell Mrs. Albert Francis (Sylvia Mae Harbaugh)"', '1   ', 'S'),
 (325, '"Sage Mr. George John Jr"', '0   ', 'S'),
 (326, '"Young Miss. Marie Grice"', '1   ', 'C'),
 (327, '"Nysveen Mr. Johan Hansen"', '0   ', 'S'),
 (328, '"Ball Mrs. (Ada E Hall)"', '1   ', 'S'),
 (329, '"Goldsmith Mrs. Frank John (Emily Alice Brown)"', '1   ', 'S'),
 (330, '"Hippach Miss. Jean Gertrude"', '1   ', 'C'),
 (331, '"McCoy Miss. Agnes"', '1   ', 'Q'),
 (332, '"Partner Mr. Austen"', '0   ', 'S'),
 (333, '"Graham Mr. George Edward"', '0   ', 'S'),
 (334, '"Vander Planke Mr. Leo Edmondus"', '0   ', 'S'),
 (335, '"Frauenthal Mrs. Henry William (Clara Heinsheimer)"', '1   ', 'S'),
 (336, '"Denkoff Mr. Mitto"', '0   ', 'S'),
 (337, '"Pears Mr. Thomas Clinton"', '0   ', 'S'),
 (338, '"Burns Miss. Elizabeth Margaret"', '1   ', 'C'),
 (339, '"Dahl Mr. Karl Edwart"', '1   ', 'S'),
 (340, '"Blackwell Mr. Stephen Weart"', '0   ', 'S'),
 (341, '"Navratil Master. Edmond Roger"', '1   ', 'S'),
 (342, '"Fortune Miss. Alice Elizabeth"', '1   ', 'S'),
 (343, '"Collander Mr. Erik Gustaf"', '0   ', 'S'),
 (344, '"Sedgwick Mr. Charles Frederick Waddington"', '0   ', 'S'),
 (345, '"Fox Mr. Stanley Hubert"', '0   ', 'S'),
 (346, '"Brown Miss. Amelia ""Mildred"""', '1   ', 'S'),
 (347, '"Smith Miss. Marion Elsie"', '1   ', 'S'),
 (348, '"Davison Mrs. Thomas Henry (Mary E Finck)"', '1   ', 'S'),
 (349, '"Coutts Master. William Loch ""William"""', '1   ', 'S'),
 (350, '"Dimic Mr. Jovan"', '0   ', 'S'),
 (351, '"Odahl Mr. Nils Martin"', '0   ', 'S'),
 (352, '"Williams-Lambert Mr. Fletcher Fellows"', '0   ', 'S'),
 (353, '"Elias Mr. Tannous"', '0   ', 'C'),
 (354, '"Arnold-Franchi Mr. Josef"', '0   ', 'S'),
 (355, '"Yousif Mr. Wazli"', '0   ', 'C'),
 (356, '"Vanden Steen Mr. Leo Peter"', '0   ', 'S'),
 (357, '"Bowerman Miss. Elsie Edith"', '1   ', 'S'),
 (358, '"Funk Miss. Annie Clemmer"', '0   ', 'S'),
 (359, '"McGovern Miss. Mary"', '1   ', 'Q'),
 (360, '"Mockler Miss. Helen Mary ""Ellie"""', '1   ', 'Q'),
 (361, '"Skoog Mr. Wilhelm"', '0   ', 'S'),
 (362, '"del Carlo Mr. Sebastiano"', '0   ', 'C'),
 (363, '"Barbara Mrs. (Catherine David)"', '0   ', 'C'),
 (364, '"Asim Mr. Adola"', '0   ', 'S'),
 (365, '"O\'Brien Mr. Thomas"', '0   ', 'Q'),
 (366, '"Adahl Mr. Mauritz Nils Martin"', '0   ', 'S'),
 (367, '"Warren Mrs. Frank Manley (Anna Sophia Atkinson)"', '1   ', 'C'),
 (368, '"Moussa Mrs. (Mantoura Boulos)"', '1   ', 'C'),
 (369, '"Jermyn Miss. Annie"', '1   ', 'Q'),
 (370, '"Aubart Mme. Leontine Pauline"', '1   ', 'C'),
 (371, '"Harder Mr. George Achilles"', '1   ', 'C'),
 (372, '"Wiklund Mr. Jakob Alfred"', '0   ', 'S'),
 (373, '"Beavan Mr. William Thomas"', '0   ', 'S'),
 (374, '"Ringhini Mr. Sante"', '0   ', 'C'),
 (375, '"Palsson Miss. Stina Viola"', '0   ', 'S'),
 (376, '"Meyer Mrs. Edgar Joseph (Leila Saks)"', '1   ', 'C'),
 (377, '"Landergren Miss. Aurora Adelia"', '1   ', 'S'),

In [9]:
table1= %sql select * from PASSAGERS
dataframe = table1.DataFrame()
dataframe

 * postgresql://postgres:***@localhost/bd_jeff
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [10]:
table2= %sql select * from TRAJET
dataframe = table2.DataFrame()
dataframe

 * postgresql://postgres:***@localhost/bd_jeff
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [13]:
table3= %sql select * from TITANIC
dataframe = table3.DataFrame()
dataframe

 * postgresql://postgres:***@localhost/postgres
891 rows affected.

,name,passengerid,survived,embarked
0,"""Braund Mr. Owen Harris""",1,True,S
1,"""Cumings Mrs. John Bradley (Florence Briggs Th...",2,True,C
2,"""Heikkinen Miss. Laina""",3,True,S
3,"""Futrelle Mrs. Jacques Heath (Lily May Peel)""",4,True,S
4,"""Allen Mr. William Henry""",5,True,S
...,...,...,...,...
886,"""Montvila Rev. Juozas""",887,True,S
887,"""Graham Miss. Margaret Edith""",888,True,S
888,"""Johnston Miss. Catherine Helen """"Carrie""""""",889,True,S
889,"""Behr Mr. Karl Howell""",890,True,C
890,"""Dooley Mr. Patrick""",891,True,Q

Phase 3 : Requetes de la base de données

■ Combien de classes de passagers différentes y avait-il à bord du Titanic ?

In [23]:
%sql select count (distinct pclass) as nombredeclasse from TRAJET;

 * postgresql://postgres:***@localhost/bd_jeff
1 rows affected.

[(3,)]

Question 2

In [28]:
%sql select distinct pclass,count(passengerid) from trajet group by pclass;

 * postgresql://postgres:***@localhost/bd_jeff
3 rows affected.

[(1, 216), (2, 184), (3, 491)]

Question 3

In [33]:
%sql select distinct pclass,sex,count(passengerid) from trajet,passagers group by pclass,sex and trajet.passengerid = passager.passengerid;

 * postgresql://postgres:***@localhost/bd_jeff
6 rows affected.

[(1, 'female', 94),
 (1, 'male', 122),
 (2, 'female', 76),
 (2, 'male', 108),
 (3, 'female', 144),
 (3, 'male', 347)]

Question 4

In [41]:
%sql select survived, count(passengerid),(count(passengerid)*100/(select count(*) from passagers)) as pourcent from passagers natural join titanic group by survived;

 * postgresql://postgres:***@localhost/bd_jeff
2 rows affected.

[('1   ', 342, 38), ('0   ', 549, 61)]

Question 5

In [89]:
%sql select pclass, count(titanic.passengerid),survived as nombre from titanic join trajet on titanic.passengerid=trajet.passengerid where titanic.survived = '1' group by trajet.pclass,titanic.survived UNION select pclass, count(titanic.passengerid),survived as nombre from titanic join trajet on titanic.passengerid=trajet.passengerid where titanic.survived = '0' group by trajet.pclass,titanic.survived;

 * postgresql://postgres:***@localhost/bd_jeff
6 rows affected.

[(3, 372, '0   '),
 (2, 97, '0   '),
 (3, 119, '1   '),
 (1, 136, '1   '),
 (1, 80, '0   '),
 (2, 87, '1   ')]

In [93]:
%sql select pclass, count(titanic.passengerid),survived,sex as nombre from titanic join trajet join passagers on titanic.passengerid = trajet.passengerid = passagers.passengerid where titanic.survived = '1' group by trajet.pclass,titanic.survived,passagers.sex UNION select pclass, count(titanic.passengerid),survived as nombre from titanic join trajet join passagers on titanic.passengerid = trajet.passengerid = passagers.passengerid where titanic.survived = '0' group by trajet.pclass,titanic.survived,passagers.sex;

 * postgresql://postgres:***@localhost/bd_jeff
(psycopg2.errors.SyntaxError) ERREUR:  erreur de syntaxe sur ou près de « = »
LINE 1: ...agers on titanic.passengerid = trajet.passengerid = passager...
                                                             ^

[SQL: select pclass, count(titanic.passengerid),survived,sex as nombre from titanic join trajet join passagers on titanic.passengerid = trajet.passengerid = passagers.passengerid where titanic.survived = '1' group by trajet.pclass,titanic.survived,passagers.sex UNION select pclass, count(titanic.passengerid),survived as nombre from titanic join trajet join passagers on titanic.passengerid = trajet.passengerid = passagers.passengerid where titanic.survived = '0' group by trajet.pclass,titanic.survived,passagers.sex;]
(Background on this error at: http://sqlalche.me/e/14/f405)